### ISSUE TITLE
有考虑过压缩后库体积的问题么？

### ISSUE THREAD

**Issue by masquevil** [heyui/heyui#1]
我写 ether-vway 的时候，一开始是使用 jquery 当做基础包，现在正通过复写其中一些简单功能取消对 jquery 的依赖。

过程中自然是使用原生 api 代替 jquery 的操作。问题在于，原生 api 都太长，比如 `document.querySelectorAll`, `document.createEvent` 之类，这些都不可被压缩。所以在考虑要不要做一些简单的封装，或者简单的做一个变量 `var doc = document` 之类，主要目的是使之可以被压缩。也可能直接不管这些就用原生 api。

目前懒得去比较具体有哪些压缩方式、具体能压缩多少，想问问你怎么看待压缩这件事？

**Comment by vvpvvp** [comment]
我现在大多数都是用原生的方式写，但是封装了addClass, removeClass这种相对比较复杂的处理。
其实我觉得相对于我们现在庞大的组件库，document.querySelectorAll这种语句并没有占据太多的空间，如果做一个简单的类，也可以，但是我现在系统真的不太多写到dom处理。

不过对于又爱又恨的jquery，这一次只能放弃它了。

不过我现在压缩后的文件大小218KB，我现在还是比较满意的，如果没有意外的外，我会把我的代码保持在400KB以内，gzip过后可以保持在100KB左右。
