### ISSUE TITLE
elementUI用起来硬邦邦的，很不舒服。楼主你这个弄得阔以，点赞！

### ISSUE THREAD

**Issue by zwl1619** [heyui/heyui#10]
elementUI、iview、还有另外一个忘了名字，用起来都是硬邦邦的，反馈差。楼主你这个可以，用起来比较舒服

**Comment by vvpvvp** [comment]
我也给自己点赞，只是都通过issue来夸heyui，这样好么...

**Comment by zwl1619** [comment]
我赶脚表单的高度可以高一点，比bootstrap稍微小一丢丢即可，差不多bulma那么大合适

**Comment by vvpvvp** [comment]
表单的高度可以调整的，按照设计的需求来做，不需要按照组件库的样式来看待这一件事情。
