### ISSUE TITLE
checkbox 自定义初始化值无效，没办法默认选中

### ISSUE THREAD

**Issue by qiuguanyou** [heyui/heyui#102]
![image](https://user-images.githubusercontent.com/24726904/56104942-812fa200-5f6c-11e9-9d21-482d2261a2ce.png)

**Comment by vvpvvp** [comment]
请提供示例，demo上面的没有问题啊？
![image](https://user-images.githubusercontent.com/7303371/56105662-f9e42d80-5f6f-11e9-96f8-4dfc696f081f.png)

**Comment by qiuguanyou** [comment]
当选项是对象时 有问题
![image](https://user-images.githubusercontent.com/24726904/56114504-98ce5100-5f93-11e9-9f60-a1712b1cc359.png)

**具体描述**
当下拉选项是对象时 ，即  [{key:1,title:'a'},{key:2,title:'b'},{key:3,title:'c'},]
设置默认值  values = [1,2]  此时 视图无法初始化默认选中

**Comment by vvpvvp** [comment]
也许是由于你的key，和title与系统设置的keyName, titleName不一致导致的。
![image](https://user-images.githubusercontent.com/7303371/56137751-0f854180-5fc8-11e9-8a71-f53a843667d1.png)
