### ISSUE TITLE
有没有滚动条组件呢

### ISSUE THREAD

**Issue by jgsrty** [heyui/heyui#103]
貌似内部是提供了的 像element一样没有开放出来 是出于什么原因呢

**Comment by vvpvvp** [comment]
内部并没有提供，是通过css样式设置的。

不使用滚动条组件，主要有以下考虑：
使用滚动条组件，由于是自定义滚动，有可能会存在很多其他组件的兼容性问题，比如说scroll事件监听不到，select下拉位置判断不到，或者无法跟随滚动。
所以，系统组件不太建议自定义的滚动组件。

第二，也是由于css现在支持自定义样式了，只是存在兼容性不强的问题。

不过，开源市场上应该有一些成熟的滚动组件，你也可以选择使用。

**Comment by jgsrty** [comment]
谢谢普及~ 🍔
