### ISSUE TITLE
建议添加按需加载, hey-util建议恢复到dependencies

### ISSUE THREAD

**Issue by kexirong** [heyui/heyui#104]
**Is your feature request related to a problem? Please describe.**
 heyui 功能越来越丰富，所以体积也渐渐变大了，目前js 380k+
 css 160k+ 加起来超过 500k, 由于hey相当于runtime, 异步加载也没意义，
加上vue.runtime core-js axios 等基础依赖，使得大于1m了
**Describe the solution you'd like**
建议做成按需加载，毕竟不是每个组件都用 的上，全量不仅浪费带宽还额外碳的排放

**Describe alternatives you've considered**
目前使用gzip, 但按需加载 gzip 将更加small
**Additional context**
谢谢，希望能考虑，作为伸手党的我祝愿heyui越来越好

**Comment by vvpvvp** [comment]
其实我考虑过按需加载的，只是，核心模块依赖比较多，如果按需加载的话，几个核心组件分别加载，最终产生的js数量将会更多，因为存在重复依赖的情况。
而就目前的打包策略上来说，我们的js和css，gzip过后，并没有特别大，而且cdn后，一次加载可以支撑好几个星期，除非你更新系统。
所以综上原因，我觉得按需加载还好，没有我们想象的那么大的需求，尤其是作为中后端系统来说。
![image](https://user-images.githubusercontent.com/7303371/56626781-b6777680-6675-11e9-88e8-021d769b37f9.png)

不过，大家对于系统的要求也越来越精细，对于按需加载的方式，我也会给出方案。
只是目前比较流行的组件库，相对来说，按需加载的方案并没有特别的好，我还是会考虑一下，如何给出一个比较好的按需加载方案的。

**Comment by vvpvvp** [comment]
具体可以参考 
![image](https://user-images.githubusercontent.com/7303371/56627268-9d6fc500-6677-11e9-9aed-0e73c3759b23.png)

**Comment by vvpvvp** [comment]
然后hey-utils，我觉得依赖很小，没有放到dependencies是防止hey-utils的更新对heyui产生影响，从安全性的角度上说，我觉得是一个很好的选择。

**Comment by vvpvvp** [comment]
按需加载已经开发完毕，等2.20.0发布。
