### ISSUE TITLE
TableItem居右对齐时，为啥就不给padding了，强迫症的人要这么难受的麽

### ISSUE THREAD

**Issue by btboys** [heyui/heyui#105]
![QQ20190424-085810](https://user-images.githubusercontent.com/841976/56625310-4b2aa600-666f-11e9-977b-b2c8944447e1.jpg)

三个方向都给 padding 就不给右边，这是出于怎样的思考方式

**Comment by vvpvvp** [comment]
主要是为了能保留更多的空间。
![image](https://user-images.githubusercontent.com/7303371/56626639-1faaba00-6675-11e9-8380-8b06022d9e7c.png)

如果你觉得难受，可以自己修改覆盖样式的。

但是我觉得你说的问题的确存在，我会把有边框的table padding修正的。

**Comment by btboys** [comment]
如果是为了节约空间，那我还能接受，不过是否可以考虑居右时，右边有 padding，左边不要 padding。

**Comment by btboys** [comment]
![QQ20190424-151456](https://user-images.githubusercontent.com/841976/56639672-d32aa300-66a3-11e9-922c-71f90cda6a06.jpg)

发现如果只在 border 的情况下修复，也不完美。😭😭😭😭

**Comment by vvpvvp** [comment]
我想了一个更好一点的办法，就是右对齐添加padding-right。
