### ISSUE TITLE
建议增加一组头像的下拉列表组件

### ISSUE THREAD

**Issue by qiuguanyou** [heyui/heyui#108]
![image](https://user-images.githubusercontent.com/24726904/56795518-3868ca80-6843-11e9-90d3-c4f56839b366.png)

建议支持 ： 单选，多选、就像现在 的 select 组件 一样

**Comment by vvpvvp** [comment]
可以自定义Dropdown 或者 Select的。

**Comment by vvpvvp** [comment]
将来会提供此类示例的
