### ISSUE TITLE
建议 table 增加自定义行样式功能

### ISSUE THREAD

**Issue by btboys** [heyui/heyui#109]
效果可以参照[iviewui的效果](https://www.iviewui.com/components/table#TDYS)

![QQ20190427-075249](https://user-images.githubusercontent.com/841976/56841704-e4e99180-68c1-11e9-85ab-74c4475ee47b.jpg)

这种需求还是很普遍。

还有一个就是 列的render不支持 html 或者组件渲染，这个也不太方便

DatePicker的清除功能做成可配置，当前日期是必填的时候，是不希望日期可以被清除的。

**Comment by vvpvvp** [comment]
列的render不支持 html 或者组件渲染 是什么意思？
heyui的table默认支持slot自定义啊？
![image](https://user-images.githubusercontent.com/7303371/56857298-4e3ed280-699e-11e9-9af9-e3ca27741b36.png)


行与列样式的确是一个问题，我会补充一下，以及 tableItem的样式，我也会补充一下。
然后DatePicker的清除功能。我觉得输入项的必填，不应该绑定在日期组件本身的，必填的校验还是建议使用js娇艳或者form校验。

**Comment by btboys** [comment]
> 列的render不支持 html 或者组件渲染 是什么意思？
> heyui的table默认支持slot自定义啊？
> ![image](https://user-images.githubusercontent.com/7303371/56857298-4e3ed280-699e-11e9-9af9-e3ca27741b36.png)
> 
> 行与列样式的确是一个问题，我会补充一下，以及 tableItem的样式，我也会补充一下。
> 然后DatePicker的清除功能。我觉得输入项的必填，不应该绑定在日期组件本身的，必填的校验还是建议使用js娇艳或者form校验。


是在column模式下的render属性不支持 html。

至于DatePicker，我描述一个场景。
我有个报表的页面，查询的时候，必须要有日期，我定义了一个 query:{} 属性用于所有查询条件的处理。并且没有查询按钮，是watch query 里面的属性变化时就进行请求。那么问题来了，DatePicker的值可以被清除掉，就导致现在这种模式，没法控制DatePicker的值不能为空了。

我不知道我说明白了我的意思了没😂。

**Comment by vvpvvp** [comment]
我明白你的意思了。
你再提一个issue吧，关于DatePicker关闭按钮的。

然后至于column模式下的render属性不支持 html，其实我还是建议使用tableItem来开发的。
column模式支持相对十分简单的table，不赞成提供太多的功能。
