### ISSUE TITLE
面包屑

### ISSUE THREAD

**Issue by liyuchuan86** [heyui/heyui#11]
能添加面包屑控件么？

**Comment by liyuchuan86** [comment]
布局 grid 需要添加跨列的配置

**Comment by vvpvvp** [comment]
面包屑控件 可以加啊，只是我们不太经常用而已。
布局 grid 添加跨列的配置是什么意思？heyui的grid本身就是跨列的，我们是24格布局容器，并不是栅格的。

**Comment by liyuchuan86** [comment]
懂了，一行中需要只需要显示中间部分的话需要2端都用列来占位

**Comment by liyuchuan86** [comment]
![image](https://user-images.githubusercontent.com/32632734/42367689-9dea848c-8137-11e8-9f2e-783336b57dfc.png)
请问这个问题怎么解决？

**Comment by vvpvvp** [comment]
breadcrumb上线啦
