### ISSUE TITLE
树形选择器交互问题

### ISSUE THREAD

**Issue by qiuguanyou** [heyui/heyui#111]
![image](https://user-images.githubusercontent.com/24726904/56873997-32543300-6a69-11e9-9499-8fea84ecea00.png)

如果显示 确定按钮， 若非点击 确定按钮 关闭下拉时，应当自动还原初始化状态。

**Comment by qiuguanyou** [comment]
还应该加一个 是否显示 底部的属性， 例如 单选的场景，选完就可以关闭了 
![image](https://user-images.githubusercontent.com/24726904/56874199-edc99700-6a6a-11e9-906f-bac7ad2b2b33.png)

**Comment by vvpvvp** [comment]
这个存在展开的时候，不小心点击选中，我会考虑一下这个问题的。

**Comment by schmurfy** [comment]
Hello, I don't read chinese but the clear button had its use even with single select.
Why not add a property to control whether it is shown or not instead of tying it to multiple selection ?

**Comment by vvpvvp** [comment]
In fact, at the beginning, I thought the switch interaction of selector was more complicated. It's better to have a confirmation button. 
Now think carefully. Everyone has different choices about this interaction form. Your suggestion is very good. I will add a property to control whether to use the confirmation button.
