### ISSUE TITLE
列表应用中 分页选择每页条数，列表数据量没有变化

### ISSUE THREAD

**Issue by frankwondon** [heyui/heyui#112]
**描述这个bug**
简洁清晰的描述这个bug是什么样子的。

**重现步骤**
步骤:  
1. 打开 '...'  
2. 点击 '....'  
3. 发现 error  

**期望行为**
清晰明了地描述你期望发生的事情。

**截图**
如果可以，添加屏幕截图帮助解释您的问题。

**请完整的描述以下信息**
 - 操作系统[比如 WIN10]
 - 浏览器[比如 chrome, safari]
 - 版本[比如 22]

**补充信息**
在这里添加关于问题的任何其他补充信息。

**Comment by vvpvvp** [comment]
请描述清楚你的问题

**Comment by vvpvvp** [comment]
这个和分页数据应该没有关系。
