### ISSUE TITLE
tree 组件 应该提供一个根据某个节点信息的方法

### ISSUE THREAD

**Issue by qiuguanyou** [heyui/heyui#115]
```

getNode(id) 

```

**Comment by vvpvvp** [comment]
请问一下，有具体的使用场景吗？

**Comment by jonsnow-7** [comment]
有的, 就是在有些表格当中需要做统计, 比如总和,平均值等, 需要在footer中展示

**Comment by qiuguanyou** [comment]
在编辑节点，或添加节点时需要展示
![image](https://user-images.githubusercontent.com/24726904/57176892-704dbe80-6e90-11e9-9916-318c64f79339.png)

**Comment by vvpvvp** [comment]
TreePicker本身就提供了方法了：
![image](https://user-images.githubusercontent.com/7303371/57187287-b5b8cd00-6f1e-11e9-95b3-2ad98bf0c8a3.png)
