### ISSUE TITLE
table组件完善

### ISSUE THREAD

**Issue by xialinlin** [heyui/heyui#116]
像table功能中合计行，还有滚动加载功能，easyui中的table很强大。可以借鉴一些功能

**Comment by vvpvvp** [comment]
其实，现在mvc的组件库，本质上，和easyui区别更大一些，我们的功能拆分的更细一些，组合能力更强，不会限制于企业级的应用。
至于滚动加载的功能，我觉得在列表中应用比较适合，如果是table的话，我的建议还是pagination。
以及合计行，其实就是多了一行合计数据，自己设置即可。
