### ISSUE TITLE
字典配置可以是异步请求吗？

### ISSUE THREAD

**Issue by qiuguanyou** [heyui/heyui#117]
例如 下这样写，请求后端，返回数组：

![image](https://user-images.githubusercontent.com/24726904/57010420-113d3f00-6c2f-11e9-998f-6759cb64e20d.png)

还有一个问题想请教一下：
在开发中遇到一种场景，一次加载字典，然后缓存起来，等有字典更新时，再手动触发刷新字典
有什么好的解决方案吗？ 通过 heyui 全局配置字典、或 全局变量配置 可以实现吗？ 
heyui 全局配置字典、 全局变量配置是响应式的吗？

**Comment by vvpvvp** [comment]
你可以参考heyui-admin，系统加载的时候，直接请求并缓存字段。
https://github.com/heyui/heyui-admin/blob/master/src/components/app/app-frame.vue#L69
如果你的需求是在使用的时候才会请求数据，请使用组件datas做处理。

**Comment by qiuguanyou** [comment]
感谢，学习了，再请教一个问题，    HeyUI.addDict(dict.name, dict.data);  支持响应式更新的吗？

遇到的场景， 添加或更新了字典，表单里的空间也需要即时更新。否则创建了字典项，发现下拉选项里还没有的情况。

**Comment by vvpvvp** [comment]
如果需要更新字典，最好在使用之前进行更新。
如果是及时更新的，不建议使用dict，其实没有组件都支持datas传递列表数据的。
