### ISSUE TITLE
Modal组件设置了style，不起作用

### ISSUE THREAD

**Issue by ffeif** [heyui/heyui#118]
**描述这个bug**
Modal组件设置了style，不起作用

**重现步骤**
步骤:  
无  

**期望行为**
style正确应用在<div class="h-modal">

**截图**
![image](https://user-images.githubusercontent.com/34880328/57015046-4c4a6d00-6c45-11e9-821b-9ef700459c8c.png)
![image](https://user-images.githubusercontent.com/34880328/57015051-540a1180-6c45-11e9-820e-53f47850fec5.png)

**Comment by vvpvvp** [comment]
请使用className进行设置
