### ISSUE TITLE
table组件

### ISSUE THREAD

**Issue by zjh599245299** [heyui/heyui#12]
1、可否添加loading状态，可以通过传入参数在table上显示一个loading状态
2、table排序的图标靠右显示总觉得很奇怪，可否改为紧跟在名称的后面，这样看起来好点

**Comment by vvpvvp** [comment]
多谢建议
其实loading的效果我是一直都在考虑的，预期下周会补充上去。
然后table的排序按钮，我刚刚试了一下，的确紧跟在名称的后面比较好看，预期下周会同时修改完毕。
