### ISSUE TITLE
建议新增一个水平 CheckBox 树形表格

### ISSUE THREAD

**Issue by qiuguanyou** [heyui/heyui#121]
![image](https://user-images.githubusercontent.com/24726904/57180615-03045280-6ebd-11e9-99e9-201b1d1016c2.png)

场景描述： 用于角色设置权限

**Comment by vvpvvp** [comment]
我建议你直接自己写一下就可以了，这个需求太特殊化了。

后期，admin系统会提供一下权限管理功能作为参考。

**Comment by qiuguanyou** [comment]
好的，有没有打算出一个， 第三方开发者组件库生态呢？ （基于 heyui 第三方开发的组件集合），就类似于 https://ext.dcloud.net.cn/
![image](https://user-images.githubusercontent.com/24726904/57186943-31644b00-6f1a-11e9-98fc-0fceafd67202.png)

**Comment by vvpvvp** [comment]
会的，我们目前正在搭建run平台。
http://run.heyui.top/
等run平台发布稳定过后，将在run平台的基础上搭建第三方开发者组件库生态。
多谢支持。
