### ISSUE TITLE
modal 组件

### ISSUE THREAD

**Issue by qiuguanyou** [heyui/heyui#122]
问题1：是否可以加入局部插入的属性呢？
![image](https://user-images.githubusercontent.com/24726904/57186854-f31a5c00-6f18-11e9-9b77-a8e1084872af.png)

[#98 ](https://github.com/heyui/heyui/issues/98)

问题2： modal 弹出后，在点击浏览器后退时，modal 不会自动关闭消失。

**Comment by vvpvvp** [comment]
问题一：
我们系统也大量使用右侧预览，所有的弹窗处理都是按照window居中的，使用起来非常流畅，如果只在预览层做modal，操作范围小，而且父级的弹框被关闭也会影响子集。
而且本身modal就是fixed，就算子集插入父级，也不会按照父级的宽度做适配。
你可以先尝试弹框使用全局的，看下有没有什么问题。

问题二
使用Modal组件即可。
js调用由于js直接调用，所以没有关联组件的周期。

**Comment by qiuguanyou** [comment]
这就尴尬了 ，项目里大量的使用了  Modal js 方式调用  



------------------ 原始邮件 ------------------
发件人: "Lan"<notifications@github.com>; 
发送时间: 2019年5月5日(星期天) 上午10:07
收件人: "heyui/heyui"<heyui@noreply.github.com>; 
抄送: "烟火里的尘埃"<570227234@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [heyui/heyui] modal 组件 (#122)




问题一：
 我们系统也大量使用右侧预览，所有的弹窗处理都是按照window居中的，使用起来非常流畅，如果只在预览层做modal，操作范围小，而且父级的弹框被关闭也会影响子集。
 而且本身modal就是fixed，就算子集插入父级，也不会按照父级的宽度做适配。
 你可以先尝试弹框使用全局的，看下有没有什么问题。
 
问题二
 使用Modal组件即可。
 js调用由于js直接调用，所以没有关联组件的周期。
 
&mdash;

**Comment by qiuguanyou** [comment]
有提供全局关闭 $Modal.allClose()   的方法吗？  我想在 路由钩子那里做一下关闭处理

**Comment by vvpvvp** [comment]
那我这边做一下

**Comment by qiuguanyou** [comment]
如果能支持指定插入  modal  ，例如 在 #app  框架路由节点那里插入，js 方式调用 modal ， 是不是也可以随着 #app 下的组件一起销毁了呢？

**Comment by vvpvvp** [comment]
我已经解决了。

**Comment by qiuguanyou** [comment]
有提供全局关闭 $Modal.allClose() 的方法吗？ 我想在 路由钩子那里做一下关闭处理
后退时解决了，但前进 push()  时候没全部关闭 $Modal

**Comment by vvpvvp** [comment]
我就想问一下，为什么会存在modal打开的时候，页面执行push？

**Comment by qiuguanyou** [comment]
例如 关闭遮罩层时，就可以点击其他菜单或链接 就会push了，应用场景，例如这样一样页面表单，我把它当 Modal 了






------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Lan"<notifications@github.com&gt;; 
发送时间: 2019年12月28日(星期六) 下午3:38
收件人: "heyui/heyui"<heyui@noreply.github.com&gt;; 
抄送: "烟火里的尘埃"<570227234@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [heyui/heyui] modal 组件 (#122)




我就想问一下，为什么会存在modal打开的时候，页面执行push？

**Comment by vvpvvp** [comment]
关闭遮罩层时，这个modal就已经销毁了啊？

**Comment by qiuguanyou** [comment]
正确操作是如你说的这样，不过也难免有一些用户，是不关闭窗口，就点了跳转的。



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Lan"<notifications@github.com&gt;; 
发送时间: 2019年12月29日(星期天) 晚上7:36
收件人: "heyui/heyui"<heyui@noreply.github.com&gt;; 
抄送: "烟火里的尘埃"<570227234@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [heyui/heyui] modal 组件 (#122)




关闭遮罩层时，这个modal就已经销毁了啊？
 
&mdash;
