### ISSUE TITLE
表单的一些需要改进的建议

### ISSUE THREAD

**Issue by layxyer** [heyui/heyui#123]
表单中的reset方法个人觉得应该是重置表单,但是实际是清除验证,form排版只有三种,建议可以增加自定义排版,即n列一行或者多增加几种排版,最多三列一行无法满足实际需求

**Comment by vvpvvp** [comment]
reset 方法我以后重置为resetValid，我接受这个建议。

至于自定义排版，我觉得三列一行已经是最多的了，基本就是两行一列，我实在是想象不出那么多一列是什么样子的交互。
而且，排版只是一个class，你可以自定义其他的排版，我觉得也不冲突。
