### ISSUE TITLE
对Table 组件 render 的建议

### ISSUE THREAD

**Issue by kexirong** [heyui/heyui#125]
目前 table组件 render函数  返回值 使用 `{{show}}` 渲染, 建议改成 v-html="show" 进行渲染 可以同时兼容纯文本 跟html 
有显示html 代码 需求 的玩家，自己处理escaped

**Comment by vvpvvp** [comment]
如果是这种的话，建议使用slot-scope，v-html="show"更加不符合需求，并且也存在安全性问题。
![image](https://user-images.githubusercontent.com/7303371/57286630-41ca2080-70e8-11e9-88e9-e68f6e0ca2b8.png)

**Comment by kexirong** [comment]
自定义表头貌似无法使用 TableItem

**Comment by vvpvvp** [comment]
我想问，自定义什么样子的表头？其实一直没有遇到过这种需求。

**Comment by kexirong** [comment]
![image](https://user-images.githubusercontent.com/31177595/57360738-7c49c100-71ad-11e9-8dda-4768c89ed02a.png)
类似例子中的，多行表头，TableItem好像不能作。只能用 ths定义，这样就只能用render，render不能渲染自定义样式了，如:某个单元格内容较长,希望超长部分...省略，然后鼠标放上或者点击时显示

**Comment by vvpvvp** [comment]
这一部分使用css就可以控制了，没有必要是要自定义啊。
新的版本即将支持 自定义样式了。

![image](https://user-images.githubusercontent.com/7303371/57421489-a3040800-723e-11e9-9b0c-2d5a0b38406f.png)

**Comment by kexirong** [comment]
文本超出确实仅 修改默认的  word-break 样式。建议提供配置，超出宽度的文本省略比多行显示有需求， 气泡提示 目前仅支持标题 。
希望能多关注表格功能。
使用heyui 等组件库做的web偏后台管理性的居多，所以丰富的表格功能能使heyui用户便利更多。
建议参考跟借鉴下 element: https://element.eleme.cn/#/zh-CN/component/table 跟antd: https://vue.ant.design/components/table-cn/

**Comment by kexirong** [comment]
我知道了 ，ths跟TableItem 可以同时用，因为例子 潜意识 以为 ths 只能用Column，看了下源码，才后知后觉
