### ISSUE TITLE
表单校验问题

### ISSUE THREAD

**Issue by qiuguanyou** [heyui/heyui#126]
**问题描述：**
   当表单选项已经隐藏时，校验还生效，导致表单无法提交也没有任何错误提示。
**希望改善：**
  有时候需要根据某个字段值的不同切换隐藏了一些字段，希望像其他UI框架那样做到，当表单项隐藏时，自动不校验，并且不提交隐藏的字段。

**Comment by vvpvvp** [comment]
当表单选项已经隐藏时，希望你的校验规则也进行变化。

![image](https://user-images.githubusercontent.com/7303371/57343753-278b5380-7177-11e9-8aa0-dbe8e50b9360.png)

具体demo:
http://localhost:9008/component/form/form#%E5%8F%82%E6%95%B0%E8%AE%BE%E5%AE%9A%E6%98%AF%E5%90%A6%E5%BF%85%E5%A1%AB

不提交隐藏的字段，这个并不包含在组件的合理需求范围内，本身Form表单是不会对数据进行处理的。
