### ISSUE TITLE
v-wordlimit，限制后长度仍大1 

### ISSUE THREAD

**Issue by kexirong** [heyui/heyui#128]
![image](https://user-images.githubusercontent.com/31177595/57361954-3a6e4a00-71b0-11e9-9559-9617df51533a.png)
如图片上姓名字段，我限制为31长度，输入框中文本长度为31，但value中值的长度为32。便于体现，用了重复的1234567890体现

**Comment by vvpvvp** [comment]
https://github.com/heyui/heyui/commit/3b19326
