### ISSUE TITLE
dropdown样式 bug

### ISSUE THREAD

**Issue by btboys** [heyui/heyui#130]
![551557388922_ pic](https://user-images.githubusercontent.com/841976/57437363-31df4780-7274-11e9-9ac6-1d0c40c98643.jpg)

![561557388966_ pic](https://user-images.githubusercontent.com/841976/57437368-373c9200-7274-11e9-8ae2-015bc2852b3a.jpg)

样式是不是应该是这样？
```
.h-dropdown-inner > div {
  border-radius: 0 0 4px 4px;
}
```

**Comment by vvpvvp** [comment]
我从官网上截图的：

![image](https://user-images.githubusercontent.com/7303371/57441155-ef216d80-727b-11e9-8eb2-5da47f889a5a.png)

你看下你的heyui版本，以及下载heyui的 dropdown.less 文件

![image](https://user-images.githubusercontent.com/7303371/57441250-1f690c00-727c-11e9-9537-c6ddc613899a.png)
