### ISSUE TITLE
button添加v-tooltip之后，hover失效

### ISSUE THREAD

**Issue by misuoka** [heyui/heyui#133]
**button添加v-tooltip之后，hover失效**
在 button 组件中添加 v-tooltip 之后，有时候 hover 失效，就是有时候移动到按钮上面，指针没有变成手指，同时怎么点也无法激发事件。

**重现步骤**
```
<Button @click="showMore = !showMore" class="icon-size" icon="icon-columns" v-tooltip="true" :content="显示更多" >更多</Button>
```

**期望行为**
不要出现这种问题

**视频**
[视频地址](http://video.wenty.xyz)，视频请留意前面的片段，当刚把鼠标移动到按钮上面时，hover失效的情形。

**请完整的描述以下信息**
 - 操作系统[MacOS]
 - 浏览器[chrome, safari]

**补充信息**
在这里添加关于问题的任何其他补充信息。

**Comment by vvpvvp** [comment]
你 content 定义错了
``` javascript
<Button @click="showMore = !showMore" class="icon-size" icon="icon-columns" v-tooltip content="显示更多" >更多</Button>
```

**Comment by misuoka** [comment]
额。我改demo的给你看的时候，忘记去掉content前的冒号了。我其实是这样用的。

`<Button @click="showMore = !showMore" class="icon-size" icon="icon-columns" v-tooltip="true" :content="showMoreContent" >{{showMoreText}}</Button>`

**Comment by vvpvvp** [comment]
你参考一下我的示例，并没有出现丢失的情况，如果有的话，请使用示例复现出来。
