### ISSUE TITLE
table的$index能不能做成从 1 开始计算？

### ISSUE THREAD

**Issue by misuoka** [heyui/heyui#134]
**table 的 $index 能不能做成从 1 开始计算**
对于非程序员来说，行号从 0 开始，实在是难以理解和习惯，建议把 table 的 $index 能不能做成从 1 开始计算。

另外建议：
1. 配置使用类似 checkbox 这种形式的配置启动行号的显示，不必要使用 `<TableItem title="" prop="$index" :width="50"></TableItem>` 这种形式配置。
2. 行号和 checkbox 这种与数据无关的列，建议可以设置强烈的颜色以区分，把行号和 checkbox 的显示与普通数据列区别开来（当然是通过配置开启）

**Comment by vvpvvp** [comment]
但是，heyui组件库是提供给程序员使用的啊。
使用0，或者1，属于个人喜好，不会作为开发标准更改的。
毕竟，我还比较喜欢从0开始。

第一个建议：我觉得既然已经有了可以展示行号的方式，就没有必要添加更多的参数。
还有，就是每个系统对于行号展示的需求不一致，所以使用以下代码能够保持自定义。
``` html
<TableItem title="" prop="$index" :width="50">
<template slot-scope="{index}">{{index+1}}</template>
</TableItem>
```
我下一回把示例修改掉，也许更清晰一点。

至于第二个建议：
用户可以自定义 `h-table-td-checkbox` 的样式，行号TableItem也可以自定义样式。
