### ISSUE TITLE
Form 的 Label 位置选项

### ISSUE THREAD

**Issue by btboys** [heyui/heyui#140]
<img width="354" alt="WX20190520-104526@2x" src="https://user-images.githubusercontent.com/841976/57993653-85f7f080-7aec-11e9-8ed8-eeb777df42e8.png">

如图所示，希望 Form 的Label可以支持位置的调整。

**Comment by vvpvvp** [comment]
![image](https://user-images.githubusercontent.com/7303371/58063222-dbe19c80-7baf-11e9-8a87-fcd1fc88ff54.png)

**Comment by btboys** [comment]
😂只能独立行了，要布局就自己写对吧

**Comment by vvpvvp** [comment]
我没有明白，你的图片不就是独立行吗？

**Comment by btboys** [comment]
😂图片是我找的一个效果给你看下。

是我没表达清楚。我的意思在两列一行和三列一行的时候也可以文字在上面。不过看到这个，好像用布局也可以搞定。

**Comment by vvpvvp** [comment]
这个你可以自己改下css就可以了。
