### ISSUE TITLE
heyadmin，ie浏览器下访问空白报错

### ISSUE THREAD

**Issue by lilifan1598** [heyui/heyui#141]
**描述这个bug**
heyadmin，ie浏览器下访问空白报错

**重现步骤**
步骤:  
1.heyadmin官网的demo页面用ie可以访问。
2.按照heyadmin脚手架的教程clone源码，项目启动后，chrome访问没问题，ie下访问报错且页面空白。

**期望行为**
ie下能正常访问

**截图**
如果可以，添加屏幕截图帮助解释您的问题。
![1558409135(1)](https://user-images.githubusercontent.com/39824392/58066282-2e748600-7bbb-11e9-9056-8d123620f9f8.jpg)

**请完整的描述以下信息**
 - 操作系统：WIN10 
 - 浏览器：ie11
 - 版本：11.765.17134.0

**补充信息**
在这里添加关于问题的任何其他补充信息。

**Comment by vvpvvp** [comment]
请问使用的是什么脚手架？
hey-cli还是vue-cli？

**Comment by lilifan1598** [comment]
先用的是hey-cli然后发现有问题，后来试了试vue-cli也一样的现象

**Comment by lilifan1598** [comment]
是的，我是通过官网的demo模板去改的：https://github.com/heyui/heyui-admin。

**Comment by vvpvvp** [comment]
请更新 hey-cli 的版本至最新
