### ISSUE TITLE
发现一点小问题

### ISSUE THREAD

**Issue by androidsr** [heyui/heyui#142]
1.日期格式化成：format="YYYYMMDD" 有值无法显示。
2.<h-sider style="height:100vh;overflow: auto">这里加上滚动条。收缩菜单收起来后无法显示子菜单。
3.建议table列可以动态设置显示/不显示。

**Comment by vvpvvp** [comment]
format="YYYYMMDD" 已经修正。

这里加上滚动条??? 这个无法理解。

建议table列可以动态设置显示/不显示。
https://www.heyui.top/component/data/view/table#%E5%9F%BA%E6%9C%AC
请参考切换列的功能。
