### ISSUE TITLE
Table 横向滚动条

### ISSUE THREAD

**Issue by wddclass** [heyui/heyui#143]
当Table满足出现横向滚动条的条件，表格内容为空时，横向滚动条不会出现。
![表格有内容](https://i.loli.net/2019/05/22/5ce4f173911d979290.png)
![表哥空内容](https://i.loli.net/2019/05/22/5ce4f25d9bb8893016.png)

**Comment by vvpvvp** [comment]
![image](https://user-images.githubusercontent.com/7303371/58228947-d5475680-7d62-11e9-93bb-35f94c8f2d09.png)
我参考了一下其他组件库的样式，这样好像也不是很好看，是否有必要无数据的时候滚动？

**Comment by wddclass** [comment]
我是觉得可能会存在虽然内容为空，但是还想看全部的表头，要不加个参数，控制是否显示空内容时的横向滚动条
