### ISSUE TITLE
AutoComplete 控件在表单中使用多选情况下无法验证通过

### ISSUE THREAD

**Issue by androidsr** [heyui/heyui#144]
AutoComplete 控件在表单中使用多选情况下无法验证通过。提示值不能为空。单选正常

**Comment by vvpvvp** [comment]
![image](https://user-images.githubusercontent.com/7303371/58224915-34509f80-7d52-11e9-86d7-9522688da65b.png)
我测试过了，并不存在这个问题，请使用vue-tool查验一下autocomplete的v-model绑定值的value
