### ISSUE TITLE
官网经常打不开， 使用梯子才正常

### ISSUE THREAD

**Issue by kexirong** [heyui/heyui#145]

**Comment by kexirong** [comment]
看F12,的网络，静态文件经常下载到一小半就一直不动了，刷新很多次会正常，使用梯子也可以正常打开。

**Comment by vvpvvp** [comment]
我使用的是阿里云，有可能是网络问题。
你使用的是什么宽带？

**Comment by kexirong** [comment]
我公司的网络。多线路负载的。别的网站没有这种现象。heyui.top 有这种情况，具体为 加载一个100多k的静态文件，会下载 十几二十k之后就不动。这个十几二十k 时会一直等超时有时直接超时，超时时控制台有js文件错误的日志打印。使用梯子能打开，说明阿里的国内线路可能部分区域不稳定

**Comment by vvpvvp** [comment]
有可能是官网的更新机制，我们并没有做缓存，所以更新后有可能会存在这个问题，强制刷新后即可正常。
