### ISSUE TITLE
使用less-loader直接从JS引入common.less时报错

### ISSUE THREAD

**Issue by TooBug** [heyui/heyui#146]
**描述这个bug**

使用less-loader，直接从JS中引入样式，会报错。

```
ERROR in ./node_modules/heyui/themes/common.less (./node_modules/css-loader/dist/cjs.js!./node_modules/less-loader/dist/cjs.js!./node_modules/heyui/themes/common.less)
Module build failed (from ./node_modules/less-loader/dist/cjs.js):



.h-func-generate-color(red);
^
Variable @red-color is undefined
      in ....../node_modules/heyui/themes/components/extend.less (line 21, column 0)
 @ ./node_modules/heyui/themes/common.less 4:14-99
 @ ....../main.ts
```

**重现步骤**

步骤:  

1. 新建入口js文件
2. 引入less文件`import 'heyui/themes/common.less';`
3. webpack添加less-loader `{test: /\.less$/,use: ['vue-style-loader', 'css-loader', 'less-loader']}`

**期望行为**

正确引入样式

**截图**

略

**请完整的描述以下信息**

 - 操作系统 MacOS 10.14.4
 - 浏览器 略
 - 版本 webpack 4.29.5 / node 10.13.0 / heyui 1.20.3

**补充信息**

文档中关于样式引入部分写得有些不太清楚，建议分成几部分：

1. 直接整体引入heyui默认样式 
2. 自定义主题色的方式引入 
3. 分模块引入

**Comment by vvpvvp** [comment]
common.less 都是在使用var.less全局变量的基础上使用的。

我把文档的优先级修改一下。

先全局变量，在vue-cli全局变量，再hey-cli全局变量

![image](https://user-images.githubusercontent.com/7303371/58299225-1433e580-7e11-11e9-8768-a8c2c3f69e09.png)

**Comment by TooBug** [comment]
我换成了引入`index.css`，就解决了。

针对文档这一块，我的意思是文档中缺失了一种用法：不做样式的定制，直接一行代码引入所有heyui样式。也就是像我一样，直接`import 'heyui/themes/index.css`。在使用npm和webpack的前提下，这种方式其实是上手最快的，但是偏偏文档中没有提及，建议补充。

**Comment by vvpvvp** [comment]
嗯嗯，接收建议。
我改一下。
