### ISSUE TITLE
Categroy异步获取数据初始数据

### ISSUE THREAD

**Issue by Thornchg** [heyui/heyui#149]
Category组件异步读取数据时的问题：
1、编写了getDatas方法后   datas这个字段就无效了
2、getDatas方法中resolve方法的调用必须在异步中  否则无效
存在需求  第一次加载时的数据   也就是级别为根数据也是动态的
例如：
getDatas: (parent, resolve) => {
          setTimeout(() => {
            if (!parent) {
              resolve([
                { id: 1, title: '一级', disabled: true },
                { id: 2, title: '二级' },
                { id: 3, title: '三级' }]);
            } else if (parent.id % 2 == 0) {
              resolve([]);
            } else {
              resolve(genList(parent.title, parent.id, 5, 'id', 'title'));
            }
          }, 100);
        }

if(!parent)为真时要解析的数据也是动态的
[
                { id: 1, title: '一级', disabled: true },
                { id: 2, title: '二级' },
                { id: 3, title: '三级' }]
这段数据也是需要向服务器异步获取后生成的
这个需求什么方式可以实现吗

**Comment by vvpvvp** [comment]
1、编写了getDatas方法后 datas这个字段就无效了
既然有getDatas方法，为什么还需要datas

2、getDatas方法中resolve方法的调用必须在异步中 否则无效
resolve是回调，并不是异步，直接返回是可以的。
直接异步调用完毕后，执行回调就可以了。
