### ISSUE TITLE
讨论：组件命名

### ISSUE THREAD

**Issue by TooBug** [heyui/heyui#15]
原码及文档中都使用了大写开头的驼峰命名，例如`TableItem` `Button`等。但按照Vue文档说明和风格指南，建议使用小写命名，并至少包含一个连字符`-`。

我看到源码中其实也有注册`h${ComponentName}`的组件，所以我在使用的时候是直接改了名字的，使用的`h-button`之类的。

建议这里遵循风格指南，组件名使用小写字母，统一以`h-`开头，尤其是像`Button`这种组件，极易与HTML原生元素混淆，分开后有利于减少混淆。

- <https://vuejs.org/v2/guide/components-registration.html#Component-Names>
- <https://vuejs.org/v2/style-guide/#Multi-word-component-names-essential>

**Comment by vvpvvp** [comment]
嗯，其实这个我是考虑过的。
按照vue的风格，其实两种都是提供了的，驼峰的方式也是可以的，只是不能应用在Dom直接渲染的开发方式中。

> 你给予组件的名字可能依赖于你打算拿它来做什么。当直接在 DOM 中使用一个组件 (而不是在字符串模板或单文件组件) 的时候，我们强烈推荐遵循 W3C 规范中的自定义组件名 (字母全小写且必须包含一个连字符)。

而我一开始计划的是，HeyUI应该是使用在单文件中的。
主要是，我觉得驼峰的写法比较好看.....好读......

不过我是计划在所有的组件文档的开头提供kebab-case的使用说明。

**Comment by vvpvvp** [comment]
嗯嗯。
因为基本上我们都是使用单文件的方式引用。
如果采用h-component-name的方式有报错，麻烦帮我提issue，多谢啦。
