### ISSUE TITLE
v1.20.0 $ImagePreview 不能弹出图片 Bug（或不能兼容旧版本写法）

### ISSUE THREAD

**Issue by gaollg** [heyui/heyui#151]
代码写法：
`this.$ImagePreview(["https://lokeshdhakar.com/projects/lightbox2/images/image-4.jpg"], 0);`

复现地址：https://codepen.io/gaollg/pen/MdLGYP

截图如下：
![image](https://user-images.githubusercontent.com/2359462/58793641-268bfb80-8629-11e9-8f11-de0dae241b78.png)

**Comment by vvpvvp** [comment]
由于 1.20.0 新增了按需加载的逻辑，所以改动比较多。
忽略了直接js引用的情况，已修正，更新至1.20.4即可。

**Comment by vvpvvp** [comment]
https://codepen.io/vvpvvp/pen/yWwMOq
