### ISSUE TITLE
Menu 组件、Pagination 组件，增加支持路由建议

### ISSUE THREAD

**Issue by gaollg** [heyui/heyui#153]
Heyui 目前 Menu、Pagination 菜单跳转由 JS 代码实现，在有些场景，需要快速打开多个窗口，以作比较。

不同的用户有不同的喜好，有些人喜欢按住 Ctrl 键 + 鼠标单击来实现，有些则喜欢鼠标拖动链接，在指定（位置）窗口打开。

故而，支持这种习惯，最好支持路由。经查，[iView Menu ](https://www.iviewui.com/components/menu)组件支持。

只是用户体验改进，Menu、Pagination 相对高频，不知是否有改进意向？

**Comment by vvpvvp** [comment]
我查看了iview的menu，并不支持啊？

**Comment by gaollg** [comment]
![image](https://user-images.githubusercontent.com/2359462/59169821-67769980-8b6e-11e9-8297-12601eddb663.png)

地址：https://www.iviewui.com/components/menu

**Comment by vvpvvp** [comment]
![image](https://user-images.githubusercontent.com/7303371/59174903-e4613d80-8b85-11e9-8145-730e7dcce060.png)
但是，它的dom结构并不支持你所描述的这些行为
> 不同的用户有不同的喜好，有些人喜欢按住 Ctrl 键 + 鼠标单击来实现，有些则喜欢鼠标拖动链接，在指定（位置）窗口打开。

**Comment by gaollg** [comment]
其实就是改进体验，如果是鼠标在链接上，左下角会有完整 URL 出现。这时点击、按住 Ctrl 点击、拖拽，都是可能的操作。

经查 iView MenuItem 源码，确实是支持 a 标签：https://github.com/iview/iview/blob/164f7bcb6ba76d73912ce19738a693e4e1c99c8e/src/components/menu/menu-item.vue#L2

![image](https://user-images.githubusercontent.com/2359462/59178167-d533bd00-8b90-11e9-99ad-e73a6fbd51f5.png)

**Comment by btboys** [comment]
menu 和DropdownMenu系列增加路由支持确实有必要，做为菜单导航的时候，要多些几句代码才能实现，确实没啥必要

**Comment by vvpvvp** [comment]
已经考虑 Menu 做实现，DropdownMenu 做 Ctrl 点击 还是比较少的。
