### ISSUE TITLE
Transfer选择的时候，触发@transfer事件，然后打印我选中的值

### ISSUE THREAD

**Issue by ruanlianjun** [heyui/heyui#154]
**Transfer选择的时候，触发@transfer事件，然后打印我选中的值**
我发现数据的第一条在选中的列表中返回的是null

但是当有2条数据的时候，再触发@transfer的时候，可以在data选中列表的数组中看到第二条，但是看不到第一条

**Comment by vvpvvp** [comment]
Transfer是执行之前的数据，包括 direction  sources  targets

你可以使用change事件
