### ISSUE TITLE
表单验证问题 

### ISSUE THREAD

**Issue by Thornchg** [heyui/heyui#155]
**描述这个bug**
1、隐藏的表单项也会验证
      >看过另外一个你的issues，这是设计如此，但是有这种需求，是否可以考虑增加一个开关
      >目前可以使用可以使用动态规则这种需求，但是较麻烦，而且好像是只能动态required，其他 
         的规则呢，自定义规则呢？或许我没有掌握到实现方式，使用computed？表单字段多呢，目 
         前的项目有个表单有十多个字段。。。

2、另一个问题是建立在动态规则上，动态required->页面刚进时，隐藏的项是不会验证了（这是理 
      想效果），但是我在切换联调开关后，这个隐藏的项出现了，这个项会进行验证了，但是我再次 
      切换开关，该项又隐藏了，但是还是会执行验证，导致表单提交不了

3、FormItem设置了label，设置错误tip提示，会有“undefined不能为空”的提示，项的红色提示语倒是没问题，tip会出现这个问题，望排查下

**期望行为**
隐藏的表单项不做验证

**截图**
如果可以，添加屏幕截图帮助解释您的问题。
<img width="947" alt="Snipaste_2019-06-13_17-42-31" src="https://user-images.githubusercontent.com/42759223/59422364-da983e00-8e02-11e9-9af2-0a9eac8885be.png">
<img width="309" alt="Snipaste_2019-06-13_17-43-44" src="https://user-images.githubusercontent.com/42759223/59422393-e421a600-8e02-11e9-9924-8f8154bb721f.png">

**补充信息**
  遇到的问题比较多，不好意思
相比较其他的的UI框架，挺喜欢这套，赞

**Comment by vvpvvp** [comment]
真的很感谢你反馈这么多实际使用中遇到的问题。
这些详细的反馈，对于我来说，帮助是非常大的。
我明天再过来仔细看下你的问题。

**Comment by vvpvvp** [comment]
第一个问题：建议使用computed属性即可。

第二个问题：是否能够提供一下简单的在线示例。

第三个问题，FormItem设置了label，然后需要对应到 prop，如果存在 undefined不能为空 的报错，那就是某一项 校验 没有设置 与 此 prop 对应的 label。
以你报错的截图为例，你的 voteInfo.planUserNumber 并没有设置对应的label。

**Comment by Thornchg** [comment]
我写了个示例，以下是代码（**label都有加**）
```
<template>
    <Form
            ref="testForm"
            :showErrorTip="true"
            :rules="validationRules"
            :validOnChange="true"
            :model="data">
        <FormItem label="类型" prop="type" :required="true">
            <Select v-model="data.type" autosize :datas="typeParams"></Select>
        </FormItem>
        <FormItem label="配置项1" prop="item1" :required="true" v-if="data.type>=2">
            <input
                    type="text"
                    v-model="data.item1"
                    placeholder="请输入配置项1"
            />
        </FormItem>
        <FormItem label="配置项2" prop="item2" :required="true" v-if="data.type>=3">
            <input
                    type="text"
                    v-model="data.item2"
                    placeholder="请输入配置项2"/>
        </FormItem>
        <FormItem label="配置项3" prop="item3" :required="true" v-if="data.type>=4">
            <input
                    type="text"
                    v-model="data.item3"
                    placeholder="请输入配置项3"/>
        </FormItem>
        <FormItem>
            <Button color="primary" @click="submit">提交</Button>
        </FormItem>
    </Form>
</template>
<script>
    export default {
        name: "test",
        data() {
            return {
                typeParams: {1: '类型1', 2: '类型2', 3: '类型3', 4: '类型4'},
                data: {
                    type: null,
                    item1: null,
                    item2: null,
                    item3: null

                },
                validationRules: {}
            }
        },
        methods: {
            submit() {
                let validResult = this.$refs.testForm.valid();
                console.log(validResult)
                if (validResult.result) {
                    this.$Message('验证成功');
                }
            }
        }
    }
</script>
```
下面是演示
![1](https://user-images.githubusercontent.com/42759223/59573269-c09d7a80-90e4-11e9-8aa8-3cae587b9fb2.gif)

问题：
item1，item2，item3三个表单项初始是隐藏的
类型选择 类型2时 item1会显示，选择类型3时 item1，item2都会显示

before：**页面刚进入后**类型选择类型1，item1，2，3，都不会显示，点击提交，**通过验证**，说明item1，2，3没有参与验证，这是正常的。

1、类型选择 类型2时，item1显示，类型切换回类型1，item1隐藏，点击提交，**提示undefind不能为空**，查看控制台  可以看到item1没有通过验证，并且没有label这个值，正常不应该再验证item1这个项

2、首先类型选择2，item1显示、点击提交（先不管是否验证成功），类型切换到类型3，item2显示出来了，然后再item1里输入文本（让item1通过验证），item2保持为空，点击提交，提示undefind不能为空，但是item2那个表单项下的错误信息确实正确的（“配置项2不能为空”）

**Comment by vvpvvp** [comment]
需要加key，这个是vue的问题。

![image](https://user-images.githubusercontent.com/7303371/59580170-af636680-9102-11e9-844a-6e1bff26440d.png)

详细可以看：
https://juejin.im/post/5b41b9cd6fb9a04fe91a5a1c
