### ISSUE TITLE
Table组件TableItem自适应宽度问题

### ISSUE THREAD

**Issue by layxyer** [heyui/heyui#156]
Table组件TableItem自适应宽度机制貌似不太好,不能根据文本宽度适当加宽,宽度都是等宽的,如果指定部分TableItem宽度,则窗口变小后,会压缩其他没有设置宽度的列,而且没有出现横向滚动,建议添加min-width和滚动条

**Comment by vvpvvp** [comment]
如果需要出现横向滚动条，则需要给每个TableItem上设置宽度。
本身自适应的机制就是table自带的机制，未做修改。
我会对文档再做补充。
