### ISSUE TITLE
checkbox 建议增加 limit 属性

### ISSUE THREAD

**Issue by qiuguanyou** [heyui/heyui#158]
**描述**
在 Checkbox  加入限制勾选数量属性 limit ， 应用场景会更灵活，例如 

**场景1：套餐的单选或多选**

![image](https://user-images.githubusercontent.com/24726904/59584940-e7be7100-9111-11e9-94ba-c90c644ec87b.png)

**场景2：套餐的单选或多选**

![image](https://user-images.githubusercontent.com/24726904/59584958-f3119c80-9111-11e9-81fd-fb9e9e93af08.png)

**Comment by vvpvvp** [comment]
但是你这些好像都不是checkbox啊？

**Comment by vvpvvp** [comment]
虽然我已经把checkbox的limit加好了.....
