### ISSUE TITLE
security holding package

### ISSUE THREAD

**Issue by DanielRuf** [heyui/heyui#160]
Hi,

it seems you have accidentally added `fs` but this is not a package on npmjs, `fs` is an internal NodeJS module.

https://github.com/heyui/heyui/blob/master/package.json#L32

See https://nodejs.org/api/fs.html

You might want to remove it using `npm uninstall fs`.

**Comment by vvpvvp** [comment]
First of all, thank you for your suggestion.
Then, fs is not used for web development, but for some build command processing.
And fs is on devDependencies, So it's ok.

See 
https://github.com/heyui/heyui/blob/master/scripts/config/hey.components.js#L11

**Comment by DanielRuf** [comment]
Sure but `fs` on npmjs is not what the internal `fs` package dies / contains.

This might confuse many. Same for `path`, `http`, `https` and more.

**Comment by DanielRuf** [comment]
Also do you know what these duplicates" on npmjs do? Some do nothing and some contain completely different code than you might expect ;-)

And these security holding packages throw warnings on some installs.

**Comment by vvpvvp** [comment]
Thank you for your reminder.
