### ISSUE TITLE
CheckBox 禁用加入数组的方式

### ISSUE THREAD

**Issue by qiuguanyou** [heyui/heyui#162]
![image](https://user-images.githubusercontent.com/24726904/59759727-4840e000-92c3-11e9-8531-fc9a9e8a6eb6.png)

**期望行为**

disabled :[1,2,3]  或 [a,b,c]

例如 有12个月份， 那么有几个相隔的月份禁止，不可点击

![image](https://user-images.githubusercontent.com/24726904/59759863-90f89900-92c3-11e9-90ec-41304b60a377.png)

**Comment by vvpvvp** [comment]
我会使用数据中的disabled属性，例如：
[{id: 1, name: 'test', disabled: true}, {id: 2, name: 'test2', disabled: true}]

将作为后期feat补充上。
