### ISSUE TITLE
建议 select 组件加入多种选择模式

### ISSUE THREAD

**Issue by qiuguanyou** [heyui/heyui#163]
![image](https://user-images.githubusercontent.com/24726904/59912622-f9bd4e00-9448-11e9-9eeb-f7dc0ad065cd.png)

**期望行为**

再多加入一种 选中一项，select 下拉列表就少一项，若在选中项中删除某一项，那么就在select列表出现某一项。这样避免已选数据造成干扰。
上图只截图了多选的模式，单选也考虑一样的交互逻辑，不同的在于，例如 有三项  a、b、c  选中了 a 那么 a从列表删除 、选中 b ，那么b从列表删除、并同时在 列表表加入 a

**Comment by vvpvvp** [comment]
这个我要说明一下，你说的这种行为存在于autocomplete中。
我们组件交互设计的基准：
交互无非是在通过不同的数据量选择不同的交互类型。

1~5个选择项单选：Radio, 或者Select
1~5个选择项多选：Checkbox, 或者Select(multiple)
5~15个选择项单选/多选：Select
15~40个选择项单选/多选：Select(filterable), 或者AutoComplete
40个以上或者需要远程模糊查询：AutoComplete

而select一般不建议超过40个选项，而一般select都控制在10个选项以内，所以你说的这种交互，其实，没有太大的必要。
