### ISSUE TITLE
建议增加tabs的位置，现在只有在顶部，有些业务或者甲方要求需要改变tabs的位置

### ISSUE THREAD

**Issue by gudufun** [heyui/heyui#164]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by vvpvvp** [comment]
![image](https://user-images.githubusercontent.com/7303371/60312055-60cc8c80-998c-11e9-8fa1-6ba72edec64e.png)
https://www.heyui.top/component/view/tabs#%E4%BD%BF%E7%94%A8%E5%86%85%E7%BD%AE%E7%9A%84%E6%A0%B7%E5%BC%8F3

Tabs 只是数据与交互的集成，样式可以自定义很多的。
