### ISSUE TITLE
可以考虑增加一个modal框可拖动的功能吗？

### ISSUE THREAD

**Issue by yundingy** [heyui/heyui#165]
**Is your feature request related to a problem? Please describe.**
有时打开的模态框较大，会遮挡一部分模态框后面的数据，用户在通过模态框录入数据时如果需要参考其他数据，会不太方便

**Describe the solution you'd like**
希望能给模态框增加一个draggable的属性，用来定义模态框是否可拖动

**Describe alternatives you've considered**
iview的模态框时可拖动的，但是我还是更喜欢heyui 😊

**Additional context**
无

**Comment by daleizi** [comment]
如果可以拖动 可以搞很多玩法

**Comment by vvpvvp** [comment]
不需要很多玩法，modal而已，玩什么啊？

**Comment by daleizi** [comment]
可以当作移动窗口来。有一些内容用户是需要对照的。如果可以移动，用户打开后，再打开别的，可以对照着看
