### ISSUE TITLE
建议 select 加入是否显示可删除选中选项功能的属性

### ISSUE THREAD

**Issue by qiuguanyou** [heyui/heyui#171]
![image](https://user-images.githubusercontent.com/24726904/60800876-8df91600-a1a8-11e9-80e0-d84710943d94.png)
![image](https://user-images.githubusercontent.com/24726904/60800983-b6811000-a1a8-11e9-99ba-b767dcedcd81.png)

当鼠标移动到框时出现 小圆删除 功能 

应用场景：例如 快速清空选中，或者在 当select 作为筛选条件时，需要点击清空选中值

**Comment by vvpvvp** [comment]
![image](https://user-images.githubusercontent.com/7303371/60933957-1d144400-a2f7-11e9-9d2e-a4681239ff7d.png)
其实select有一个请选择项，用来做清空处理的。

**Comment by qiuguanyou** [comment]
加上 小圆删除 一个点击就可以清空了，更加快捷。  这样选中的不太好，需要点击两次才可以清空，第一次得点击输入框，第二次得点击选中 。 当然这属于更人性化优化，建议可以加上，让 heyui 更完美

**Comment by vvpvvp** [comment]
我已经计划加上了，正在计划中。

**Comment by qiuguanyou** [comment]
感谢采纳！
