### ISSUE TITLE
建议  FormItem 也加入 labelWidth 字段

### ISSUE THREAD

**Issue by qiuguanyou** [heyui/heyui#172]
可以像 element-ui 那样实现单独控制某个  FormItem 的  labelWidth

**Comment by vvpvvp** [comment]
为什么呢？有哪一些应用场景？

**Comment by qiuguanyou** [comment]
1、场景一：分段表单，即在表单字段再嵌套表单多个字段时，最外层的 labelWidth 需要设置为 0

![image](https://user-images.githubusercontent.com/24726904/61019158-bf9df700-a3cb-11e9-818d-c391c29538e1.png)



2、场景二：当某个字段需要单独 设置 labelWidth  时，  element-ui 也有提供这样的单独的设置，觉得比较灵活，所以在此提议。

**Comment by vvpvvp** [comment]
不建议使用嵌套多个字段，建议配合showLabel，single属性进行配合开发。

> 当某个字段需要单独 设置 labelWidth 时
这种需求，我们使用的2年的情况下也没有遇到过这种需求。

多谢你提供的建议。
