### ISSUE TITLE
Format date in dateRangePicker

### ISSUE THREAD

**Issue by dougjuliao** [heyui/heyui#175]
Hello Lan,
Has a way to implement a format date to daterangepicker ?
when i do it i receive a bug in this component:
`<DateRangePicker v-model="value" format="DDMMYYYY"></DateRangePicker>`

i trying to fork this repository anda run the develop, but i am get somes problems when i run `hey dev`

**Comment by vvpvvp** [comment]
Please update heyui@1.23.2
