### ISSUE TITLE
再次提表单校验问题

### ISSUE THREAD

**Issue by qiuguanyou** [heyui/heyui#182]
**描述Bug1**

是一个切换显示或隐藏的表单项校验，如果隐藏时触发了校验后，再次切换为显示，再次触发校验，则无法校验，没有任何提示。

```
 <FormItem label="客户" prop="customer_id"  v-if="ishow">
       <input type="text" v-model="objFormModel.receiver_user" placeholder="请输入寄件人"/>
 </FormItem>
```
   

1.   ishow ：默认是 false
2.  当ishow = false 时，点击提交表单，会触发一次校验，这个时候 这个表单项并不存在显示。
3.  重点问题来了 ，当把 ishow = true 时， 再次提交表单  ，
4.  那么该显示出来的表单项无法校验，即没有生效

---
**描述Bug2**

当我自定义封装一个 v-model 组件时，已经在组件里   this.$emit('input',data)  但无法触发校验，
即没办法清空之前的校验错误提示。还原步骤：

1、创建一个自定义组件 ，带有 v-model 的
2、把自定义组件 用 FormItem  包含起来。像 heyui 内置组件一样的使用。
3、点击提交表单按钮，先让表单触发校验，让自定义的组件项出现校验错误的提示，例如不能为空
4、给自定义组件输入值，即让 v-mode 有值，重点问题来了，此时并不会清空 上次的校验错误。

**最后建议，官方文档加入，怎么结合heyui 表单组件 和校验，开发自定义表组件的案例，以及动态切换表单动态校验的案例**

**Comment by vvpvvp** [comment]
多谢你的建议。

关于问题1：
触发校验的是rules，如果你rules添加了必填校验，那不管是否有这个输入项，数据都会做校验。
建议使用 FormItem 的 required 属性。
具体参考：
https://www.heyui.top/component/form/form#%E5%8F%82%E6%95%B0%E8%AE%BE%E5%AE%9A%E6%98%AF%E5%90%A6%E5%BF%85%E5%A1%AB

问题2：
此类信息的缺失，的确是一个问题，我会后续补充上相关说明的。

然后，由于内部组件的$emit，Form是没有办法监听的，所以需要使用html事件触发。
以其他组件为例：
``` javascript
let event = document.createEvent('CustomEvent');
event.initCustomEvent('setvalue', true, true, value);
this.$el.dispatchEvent(event);
```

**Comment by qiuguanyou** [comment]
第一个问题： 如果 表单项一直是显示的，那么没问题，可以正常校验。 还原操作步骤：
1、先把动态校验的表单项隐藏
2、点击表单提交触发表单校验
3、把动态校验的表单项切换显示出来
4、继续再次点击表单提交触发表单校验，而这个时候并不会触发 动态校验的表单项

**Comment by qiuguanyou** [comment]
![image](https://user-images.githubusercontent.com/24726904/61105635-14fe0500-a4ad-11e9-9257-d5ffccb25a60.png)
可以运行heyui 文档案例，加入 v-if 判断试试

**Comment by qiuguanyou** [comment]
![image](https://user-images.githubusercontent.com/24726904/61105828-a7060d80-a4ad-11e9-9487-ffc76c67b6be.png)
DOM 的提示并没有再触发

**Comment by vvpvvp** [comment]
请把你的代码贴到issue中，这样我才好复现。
多谢。

**Comment by qiuguanyou** [comment]
@vvpvvp 
![image](https://user-images.githubusercontent.com/24726904/61197189-19712a80-a706-11e9-8b58-cb05c860103c.png)
`<template>
  <div>
    <Form :label-width="110" :model="data" ref="form" :rules="rules" :showErrorTip="showErrorTip">
      <FormItem>
        <Checkbox v-model="required">是否必填</Checkbox>
        <i class="h-split"></i>
        <Checkbox v-model="showErrorTip">是否使用Message提示错误信息</Checkbox>
      </FormItem>
      
      <FormItem label="自定义数组" prop="list[0]" v-if="required" :required="required">
        <input type="text" v-model="data.list[0]" />
      </FormItem>
      <FormItem label="自定义规则" prop="value" :required="required">
        <input type="text" v-model="data.value" />
      </FormItem>
      <FormItem :no-padding="true">
        <Button color="primary" @click="submit">提交</Button>
        <Button @click="reset">清除验证</Button>
      </FormItem>
    </Form>
  </div>
</template>
<script>
export default {
  data() {
    return {
      required: true,
      showErrorTip: true,
      data: {
        list: [null],
        value: null
      },
      rules: {}
    };
  },
  watch: {
    required() {
      this.$refs.form.resetValid();
    }
  },
  methods: {
    submit() {
      let validResult = this.$refs.form.valid();
      if (validResult.result) {
        this.$Message('验证成功');
      }
    },
    reset() {
      this.$refs.form.resetValid();
    }
  }
};
</script>
`

**还原步骤**

1、先勾选 去掉必填  如图
![image](https://user-images.githubusercontent.com/24726904/61197217-4e7d7d00-a706-11e9-94a6-89149f21ec2f.png)
2、点击确定提交触发一次表单校验（这次正常的）
3、再次勾选必填，这个时候 v-if 的必填项出来的了 ，如图
![image](https://user-images.githubusercontent.com/24726904/61197269-900e2800-a706-11e9-83a7-35b21fe36d79.png)
4、再次点击提交触发表单校验，这个时候就有问题了 ，如图：
![image](https://user-images.githubusercontent.com/24726904/61197323-cd72b580-a706-11e9-95d3-b12820a4a200.png)
