### ISSUE TITLE
Uploader 组件的困惑

### ISSUE THREAD

**Issue by kexirong** [heyui/heyui#183]
![image](https://user-images.githubusercontent.com/31177595/61122896-94073380-a4d5-11e9-80e4-a2f77565ad14.png)
上图是我参考 文档上的demo 使用 uploader 组件，点击上传选择文件后，下面出现一个 图中红框
的进度条dom，同时控制台打印一个错误，plupload 停止工作。

**Comment by vvpvvp** [comment]
进度条是正常的，建议你跟进一些是哪里的报错信息。

**Comment by kexirong** [comment]
谢谢回复，找到问题了，配置的原因，复制demo参数没有仔细去阅读plupload的文档，导致这种报错的
