### ISSUE TITLE
建议增强树型表格方法

### ISSUE THREAD

**Issue by qiuguanyou** [heyui/heyui#185]
![image](https://user-images.githubusercontent.com/24726904/61284886-777b3c00-a7f2-11e9-88cc-8e8f4719e2cf.png)

**Comment by vvpvvp** [comment]
请问你们在实际项目应用中有这种需求吗？

**Comment by qiuguanyou** [comment]
@vvpvvp 全部展开 和 全部折叠功能 、自定义 展开和收起icon  这样的需求是有的

**Comment by vvpvvp** [comment]
比如?

**Comment by qiuguanyou** [comment]
比如财务系统
![image](https://user-images.githubusercontent.com/24726904/61506276-28acec80-aa14-11e9-9c14-9b1fca6dc683.png)

**Comment by btboys** [comment]
不能设置默认全部展开么?

**Comment by vvpvvp** [comment]
我正在计划做，展开和收起的控制。

**Comment by kexirong** [comment]
我在使用树表格的时候，添加或者删除 数据中的 children中元素，表格不会实时响应 @vvpvvp

**Comment by wushengbo** [comment]
怎么控制   tableTree 全部展开与全部收缩
