### ISSUE TITLE
建议 TreePicker 树下拉选择 加入默认展开属性

### ISSUE THREAD

**Issue by qiuguanyou** [heyui/heyui#187]
![image](https://user-images.githubusercontent.com/24726904/61369902-bd540500-a8c3-11e9-80a5-120f55a3bab3.png)

场景例如 部门选择， 公司是为最顶级，如果一打开就只看到公司这一级体验不够好，如图：
![image](https://user-images.githubusercontent.com/24726904/61370096-289dd700-a8c4-11e9-9aef-e72fe2115267.png)

希望支持设置默认展开属性， 最终效果如图：
![image](https://user-images.githubusercontent.com/24726904/61369945-df4d8780-a8c3-11e9-86c0-0cfc99d06819.png)

**Comment by vvpvvp** [comment]
#213
