### ISSUE TITLE
DatePicker 日期控件 format 属性有问题

### ISSUE THREAD

**Issue by qiuguanyou** [heyui/heyui#191]
**描述这个bug**

![image](https://user-images.githubusercontent.com/24726904/61503668-390c9980-aa0b-11e9-99d3-c29d6a30ec40.png)

选择月 ，例如 我选了 12 月， 输入框显示的值是  11 月，总是少了一个月，并且再次打开一直是选中在电脑当前月，例如现在的7月， 不过 v-model="value" 显示的值是正确的 12 月。

**重现步骤**
```
<template>
  <div>
      <p><SwitchList v-model="type" :datas="{year: '年', month: '月', quarter: '季度', week: '周', date: '日'}"></SwitchList></p>
      <p>value:{{value}}</p>
      <DatePicker v-model="value" :type="type" format="YYYY-MM"></DatePicker>
  </div>
</template>

<script>
export default {
  data() {
    return {
      value: '',
      type: 'date'
    };
  }
};
</script>

```

**Comment by vvpvvp** [comment]
请等版本更新，并更新manba版本。

**Comment by qiuguanyou** [comment]
好的 谢谢




------------------ 原始邮件 ------------------
发件人: "Lan"<notifications@github.com>; 
发送时间: 2019年8月1日(星期四) 下午3:47
收件人: "heyui/heyui"<heyui@noreply.github.com>; 
抄送: "烟火里的尘埃"<570227234@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [heyui/heyui] DatePicker 日期控件 format 属性有问题 (#191)




请等版本更新，并更新manba版本。
 
&mdash;
