### ISSUE TITLE
面包屑的样式问题

### ISSUE THREAD

**Issue by fanzouguo** [heyui/heyui#20]
Breadcrumb 面包屑加了图标后，上下没有对齐，是否可以处理为图标与文字垂直居中对齐？

**Comment by fanzouguo** [comment]
PS：算了，我用自定义样式与执行来处理吧

**Comment by vvpvvp** [comment]
<img width="351" alt="2018-09-18 7 49 36" src="https://user-images.githubusercontent.com/7303371/45664990-75cfe180-bb17-11e8-82e3-fd7dbed7c647.png">
我的demo好像就是垂直剧中的，我不知道为什么你的没有上下对齐？

**Comment by fanzouguo** [comment]
我也没有查到原因，最后用了终极大法，纯文字 ：)

**Comment by vvpvvp** [comment]
应该是vertical-align:middle的问题
