### ISSUE TITLE
menu是否可以做横向的

### ISSUE THREAD

**Issue by rongxingsun** [heyui/heyui#205]
![图片](https://user-images.githubusercontent.com/12825624/62438927-40a69f00-b77c-11e9-997a-45d98851c493.png)

**Comment by vvpvvp** [comment]
已经做了，正在考虑发布。

**Comment by rongxingsun** [comment]
还有横向宽度不够时能否自动折叠
![图片](https://user-images.githubusercontent.com/12825624/62446579-9f2c4700-b795-11e9-81ed-1a5a0def88c4.png)

**Comment by vvpvvp** [comment]
https://www.heyui.top/component/view/menu#%E6%B0%B4%E5%B9%B3%20Menu%20%E8%8F%9C%E5%8D%95

但是，目前还没有做自动折叠的，这个需要js做控制，后期和 #203 这个bug一起修正。
