### ISSUE TITLE
 menu

### ISSUE THREAD

**Issue by kvsl9** [heyui/heyui#207]
menu 组件是能考虑加上默认展开子项，类似element ui 中navmenu 中的 default-openeds 属性。

**Comment by vvpvvp** [comment]
建议直接使用方法执行，可以达到相同的效果。
![image](https://user-images.githubusercontent.com/7303371/62454962-eb808280-b7a7-11e9-9883-505dbb5b9c90.png)

**Comment by kvsl9** [comment]
示例是选中事件，并且只能单选，是否可以考虑menu可以允许几个子项展开的配置呢？

**Comment by vvpvvp** [comment]
我想问清楚一下，为什么会有这种需求呢？

**Comment by kvsl9** [comment]
目的就是为了好看一点，当侧边栏的一级菜单少(用户获取授权可能只有1-2个)的情况下，能把子项显示出来让侧边栏看起来会丰满。
