### ISSUE TITLE
switch  错位

### ISSUE THREAD

**Issue by rongxingsun** [heyui/heyui#208]
官方例子应该主题色时switch打开状态错位
switchlist也是这样

https://www.heyui.top/component/form/switch
随便选一个主题色

![图片](https://user-images.githubusercontent.com/12825624/62502736-997d4280-b823-11e9-8b3d-4df1e3a5d807.png)

**Comment by vvpvvp** [comment]
多谢你的提醒，是由于我的多主题没有重新生成的问题，我补充一下。
