### ISSUE TITLE
h-transfer  组件优化建议

### ISSUE THREAD

**Issue by qiuguanyou** [heyui/heyui#210]
**期望行为**
1、增加searchKey ，（解决现在搜索必须存在 text 字段的问题）
2、在搜索输入框加入 快捷清空输入按钮 
![image](https://user-images.githubusercontent.com/24726904/62849814-aadab900-bd13-11e9-94fe-3bd6062bba01.png)
3、无数据时，建议搜索框一起隐藏
4、加入内容插槽自定渲染，就是实现如下图自定义渲染 
![image](https://user-images.githubusercontent.com/24726904/62849914-f8572600-bd13-11e9-8a0c-a3cdaea865ab.png)

**Comment by vvpvvp** [comment]
多谢你的建议。
我觉得你的建议都非常的棒，我们将在下一期迭代中，补充这些功能。

**Comment by qiuguanyou** [comment]
感谢采纳建议， 你是最棒的， 开源了一个这么好用的框架 ！ 👍  ，建议再多加入一个设置 高度的属性
现在我是通过  .h-transfer .h-transfer-source .h-transfer-list {max-height: 160px!important;} 这样设置的， 不够方便。设置高度的需求也是存在的。感谢感谢！

**Comment by qiuguanyou** [comment]
@vvpvvp 感谢采纳建议， 你是最棒的， 开源了一个这么好用的框架 ！ 👍 ，建议再多加入一个设置 高度的属性
现在我是通过 .h-transfer .h-transfer-source .h-transfer-list {max-height: 160px!important;} 这样设置的， 不够方便。设置高度的需求也是存在的。感谢感谢！

**Comment by vvpvvp** [comment]
我觉得这个也是比较实用的需求。

还有，内容插槽自定渲染，目前transfer已经支持了，我不太确定你说的是不是和我理解的不一致。
https://www.heyui.top/component/view/transfer#%E8%87%AA%E5%AE%9A%E4%B9%89

**Comment by qiuguanyou** [comment]
@vvpvvp 内容插槽自定渲染 挺好的， 不过如果还可以支持两边分别不同的内容插槽自定渲染，那更灵活了。
