### ISSUE TITLE
this.$Modal可以使用Rate组件吗？怎么用？

### ISSUE THREAD

**Issue by zhaoxiong123** [heyui/heyui#216]
this.$Modal可以使用Rate组件吗？怎么用？

**Comment by vvpvvp** [comment]
你想要怎么用？

**Comment by zhaoxiong123** [comment]
就是弹出层里面显示评分组件，请问怎么用，不太清楚😂

**Comment by vvpvvp** [comment]
有很多种方式，你可以参考官方文档。
vue调用示例中，有select组件。
https://www.heyui.top/component/message/modal#Modal%E5%8F%82%E6%95%B0
