### ISSUE TITLE
按需加载组件  分页

### ISSUE THREAD

**Issue by Thornchg** [heyui/heyui#218]
**描述这个bug**

*
![image](https://user-images.githubusercontent.com/42759223/63632372-574b6200-c667-11e9-9290-f605ff068210.png)
*重现步骤**
步骤:  
1. 打开 '...'  
2. 点击 '....'  
3. 发现 error  

![image](https://user-images.githubusercontent.com/42759223/63632376-629e8d80-c667-11e9-9a22-5285cfd3cd21.png)
**期望行为**
清晰明了地描述你期望发生的事情。

**截图**
如果可以，添加屏幕截图帮助解释您的问题。

**请完整的描述以下信息**
 - 操作系统[比如 WIN10]
 - 浏览器[比如 chrome, safari]
 - 版本[比如 22]

**补充信息**
在这里添加关于问题的任何其他补充信息。

**Comment by vvpvvp** [comment]
等待版本更新至**heyui@1.25.0**
