### ISSUE TITLE
table设置fixed ，设置定高时出现的问题

### ISSUE THREAD

**Issue by Thornchg** [heyui/heyui#222]
![1](https://user-images.githubusercontent.com/42759223/63989635-92d8a700-cb13-11e9-8d26-4cb202e362e3.gif)

table设置定高400  高于400时出现滚动条
场景：
table分页
第一页数据10条，table高度高于400，出现上下滚动条
翻到第二页，数据只有5条，table高度小于400，滚动条消失，fixed的列出现偏移，导致看到了后面的内容，拉动浏览器，变换浏览器的宽高，恢复正常，具体看动图

**Comment by vvpvvp** [comment]
收到，下期修复。

**Comment by vvpvvp** [comment]
请说明一下浏览器信息，官网并未复现出相关现象。

**Comment by Thornchg** [comment]
chrome 77

**Comment by vvpvvp** [comment]
https://www.heyui.top/component/data/view/table#Table%20%E5%86%85%E5%AE%B9%E6%BB%9A%E5%8A%A8

那你看下这个demo你运行有问题吗？

**Comment by Thornchg** [comment]
我也无法重现了。。。。
我试了项目的现在也是正常的，不清楚是否是浏览器的问题
