### ISSUE TITLE
DropdownMenu 下拉菜单一个问题

### ISSUE THREAD

**Issue by wangzhaojun** [heyui/heyui#229]
![issue](https://user-images.githubusercontent.com/13249982/65145814-ff78fe80-da4c-11e9-8ae7-2acba2b8e1eb.gif)
第一次点击是正常的，当滑动滚动条的时候 他的样式就变了，我padding 右边50个px 还是跑右边去了，需要点击其他组件才会恢复原样。

**Comment by vvpvvp** [comment]
这个我知道的，你把下面的dropdown加一下宽度。
