### ISSUE TITLE
关于switch组件

### ISSUE THREAD

**Issue by fanzouguo** [heyui/heyui#23]
场景1：后台返回值为 0、1，每次获取后，都要人为去转换一下，稍微忘记都不行。是否可以从组件级自动判断 -1、0、1，这样的值；

场景2：比如：想用字段 nullAble 代表是否可为空，DB值为 0：不可为空，1：允许为空。但在前端页面控件的LABLE名称为”是否必填“，因此当值为 0时，反而需要组件显示为 “打开”状态。

在这个特性上，比较赞同 iview的处理方法，有两个 api：true-value 和 false-value，这样可以个性控制，满足任意场景。

**Comment by vvpvvp** [comment]
之前我们也遇到这个问题，我觉得这个建议非常好，我明天参考iview优化一波。
