### ISSUE TITLE
表单读写分发器 —编辑/详情 的合并

### ISSUE THREAD

**Issue by daleizi** [heyui/heyui#233]
编辑页和详情页，除了一个用来编辑，一个用来展示。 具体查看 https://juejin.im/post/5d9bfb1df265da5bb318e3d4

**Comment by vvpvvp** [comment]
这个太简单了，对于复杂业务的处理，还是不实用，不过，如果你觉得比较适用于比较简单的需求，我觉得你可以直接自己尝试基于heyui做出扩展支持。
