### ISSUE TITLE
category增加全选与清空选中项功能

### ISSUE THREAD

**Issue by Thornchg** [heyui/heyui#236]
如题
category望能够增加全选与清空选中项的功能
全选：比如100项里要选择90多项，需要勾选90多个，增加全选，先全选再去掉不需要的项

**Comment by vvpvvp** [comment]
由于Category本身是树结构，如果这样执行，还是会存在交互以及数据的问题。
而且本身多选90多项，category的交互形式已经不满足这种需求了。
我建议你使用自定义DropdownCustom，自己开发符合自己需求的组件。
