### ISSUE TITLE
FormItem添加rules

### ISSUE THREAD

**Issue by nyrf** [heyui/heyui#244]
**Is your feature request related to a problem? Please describe.**
表单验证rules现在是加在Form上的，因为在做一些功能时，用户自定义的字段，验证加在字段上，现在只能加在Form上，如https://element.eleme.io/#/zh-CN/component/form#form-item-attributes

**Comment by vvpvvp** [comment]
验证加在字段上，使用rules也是没有问题的。
如果不是必填项的校验，可以直接加上，没有这个字段，对于最后的提交也不影响。
如果是必填项的校验，FormItem上面已经支持required的单独定义了。
如果是根据某些参数来做校验，我建议你直接写valid就可以解决这个问题了。

**Comment by nyrf** [comment]
其实这个主要是我们用来做拖拉表单设计用的，我现在自己改了formitem，加了prop `rules: Object`
```vue
mounted() {
    if (this.prop) {   
      if (this.rules) {
        this.setConfig(this.prop, this.rules)
      } else if (this.required) {
        this.setConfig(this.prop, { required: this.required });
      }
      this.errorMessage = this.updateErrorMessage(this.prop, this.label);
    }
  }
```
另外还有一点就是现在input 和 textarea直接用的原生的，input event传过去的和其它的组件不一样，其它的emit后传的都是value，这两个原生的是$event，是不是把这两个也封装了，统一组件的input事件？

**Comment by vvpvvp** [comment]
原生的change事件，本身formitem组件也是监听的。

**Comment by nyrf** [comment]
我知道是监听的，现在主要这两个组件和其它的不统一，我现在就是分开处理了，其它比如Checkbox或者Radio，都有个input的event，然后直接返回的就是value，我现在对input和textarea是特别处理了下，这两个的event返回和其它组件不一样，比如element ui，就是所有组件的事件返回是统一的。

**Comment by vvpvvp** [comment]
就算对input和textarea特殊处理，也不可能是改成input事件，这样会造成input事件和原生的input事件重叠了。

**Comment by nyrf** [comment]
我看element ui好像组件都有个input事件，返回的都是value
