### ISSUE TITLE
怎样控制Table-Tree 全部展开显示

### ISSUE THREAD

**Issue by wushengbo** [heyui/heyui#245]
怎样控制Table-Tree 全部展开显示，而不是需要手动点击展开箭头
![image](https://user-images.githubusercontent.com/42960702/67838261-de1b3000-fb2b-11e9-98b6-b3f75a98bcec.png)
![image](https://user-images.githubusercontent.com/42960702/67838282-e6736b00-fb2b-11e9-9066-9f4638b1a6f2.png)

**Comment by vvpvvp** [comment]
计划中，最近比较忙，后期会上。

**Comment by qiuguanyou** [comment]
@vvpvvp 小姐姐，问一下Table-Tree全部展开显示 方法，什么时候发布支持呢？
