### ISSUE TITLE
Grid 布局是否可以增加栅格间偏移量，不是指space-x, space-x, space-y这种间距

### ISSUE THREAD

**Issue by fanzouguo** [heyui/heyui#25]
类似于 offset-x ，就可以让 col 和前一个 col 间隔 x 个 栅格

**Comment by vvpvvp** [comment]
其实heyui的栅格和其他的不太一样，能列举一下应用场景吗？
当时由于没有想到真实的应用场景，所以，就没有添加这种属性。

**Comment by fanzouguo** [comment]
主要还是在布局场景，比如说需要以下的布局样式，
![default](https://user-images.githubusercontent.com/10015003/45919760-1d109800-becd-11e8-9cd0-b8733b969261.png)
在目前的情况下，只能将中间的 Col宽度设为 14，然后再自己去处理这个 Col 内的元素，使其只占 14 cell  中的 4 cell，而我实际需要的只是 width=4，在这种情况下，可能会存在 与上一行对齐上的困扰，比如 4 / 14 不能整除，也无法通过固定的 px 等方式去处理。

**Comment by fanzouguo** [comment]
补充说明一下，这个问题本来是在表单布局的时候遇到的。由于目前 form最多支持 3 列，遇到更多列的时候，只能改用 row 布局，但并非每行存在的列元素都一样多，需要控制位置时，就遇到了这个需求。

**Comment by vvpvvp** [comment]
如果是这样的需求，我建议使用：
``` html
<Row>
<Col :width="6"></Col>
<Col :width="4"></Col>
<Col :width="10"></Col>
<Col :width="4"></Col>
</Row>
```
