### ISSUE TITLE
多环境配置问题

### ISSUE THREAD

**Issue by linda89** [heyui/heyui#252]
问题描述
1.有测试环境，线上环境和开发环境，分别要配置不同的服务器地址。
 "scripts": {
    "serve": "hey dev",
    "build": "hey build",
    "test" : "hey build -f hey.conf.test.js",
      }
switch (process.env.NODE_ENV) {
    case 'development':
        baseUrl = "https://xy/model/api"  //这里是本地的请求url
        break
    case 'test':   //
        baseUrl = "https://yun.xy.cn/model/api"  //这里是测试环境中的url
        break
    case 'production':
        baseUrl = "https://xy.cn/model/api"   //生产环境url
        break
}
问题是打包时可以用test命令，但是路径还是production对应的baseUrl
请教大佬 ，多谢

**Comment by vvpvvp** [comment]
我先说一下我们项目处理。
我们只使用webpack反向代理来配置开发环境，等到了测试环境以及生产环境，都是使用nginx配置反向代理，后端请求是不会写死在代码里面的。
