### ISSUE TITLE
Menu菜单二级条目太多，显示不全

### ISSUE THREAD

**Issue by yueyaww** [heyui/heyui#256]
Menu菜单二级条目太多，显示不全

![图片](https://user-images.githubusercontent.com/49739029/69793434-62340680-1203-11ea-8bfe-4a15e0348e9f.png)
。。。
![图片](https://user-images.githubusercontent.com/49739029/69793447-6829e780-1203-11ea-9372-8ad7ea9577df.png)
大概超过25个就显示不全了

**Comment by vvpvvp** [comment]
未来会切换成translation，但是目前是由于特效的max-height，你可以自己在项目里面改写一下。
