### ISSUE TITLE
Table 单选框 this.$refs.table.getSelection() 无法获取数据

### ISSUE THREAD

**Issue by wangzhaojun** [heyui/heyui#259]
描述： 
table 我用了Radio选择数据 使用 this.$refs.table.getSelection() 这个方法无法获取到选择的数据，
checkbox 是可以获取到数据的,我尝试在官网的例子当中试了下也是这样的
![1575619188(1)](https://user-images.githubusercontent.com/13249982/70306298-77331a00-1841-11ea-8ef0-99500dc84752.jpg)
疑问：
是不是我打开的方式不对？

**Comment by vvpvvp** [comment]
你在remove的地方加，这一行数据不是已经删除了吗？

**Comment by wangzhaojun** [comment]
没有  大大，我注释掉了删除的代码
![1575943591(1)](https://user-images.githubusercontent.com/13249982/70488797-c70d2c00-1b34-11ea-8ae0-521c580b713a.jpg)

**Comment by vvpvvp** [comment]
你能把这个代码放在issue里面吗？

**Comment by wangzhaojun** [comment]
描述这个bug
单选框 this.$refs.table.getSelection()

重现步骤
1、打开 https://www.heyui.top/run
2、粘贴如下代码运行

结果如上个图,麻烦了
`<template>
  <div>
    <p><SwitchList v-model="mode" small :datas="{'checkbox': '多选', 'rowSelect': '单选'}"></SwitchList></p>
    <p v-if="mode=='rowSelect'">
      <h-switch v-model="useRadio" small>使用Radio / Use radio</h-switch>
      <Button size="s" @click="setRowSelect">选中第一行 / Select the first line</Button>
      <Button size="s" @click="reset">清空选择 / Clear</Button>
    </p>
    <p v-else>
      <Button size="s" @click="invereSelection">反向选择 / Inverse selection</Button>
      <Button size="s" @click="setOddSelection">选择奇数列 / Select odd columns</Button>
      <Button size="s" @click="reset">清空选择 / Clear</Button>
    </p>
    <Table :datas="datas" ref="table" :height="400" @select="onselect" :checkbox="mode=='checkbox'" :selectRow="mode=='rowSelect'" :radio="mode=='rowSelect' && useRadio" selectWhenClickTr>
      <TableItem title="ID" prop="id" align="center" :width="80" fixed="left"></TableItem>
      <TableItem title="age" prop="age" :width="150"></TableItem>
      <TableItem title="address" prop="address" align="center" :width="150"></TableItem>
      <TableItem title="name" prop="name" :width="150"></TableItem>
      <TableItem title="age" prop="age" :width="150"></TableItem>
      <TableItem title="address" prop="address" align="center" :width="150"></TableItem>
      <TableItem title="name" prop="name" :width="150"></TableItem>
      <TableItem title="age" prop="age" :width="150"></TableItem>
      <TableItem title="address" prop="address" align="center" :width="150"></TableItem>
      <TableItem title="operating" align="center" :width="80" fixed="right"><template slot-scope="{data}"><button class="h-btn h-btn-s h-btn-red" @click="remove(datas, data)"><i class="h-icon-trash"></i></button></template></TableItem>
      <div slot="empty">Custom reminder: no data at this time</div>
    </Table>
  </div>
</template>

<script>
export default {
  data() {
    return {
      datas: [],
      useRadio: true,
      mode: 'rowSelect'
    };
  },
  mounted() {
    setTimeout(() => {
      this.datas = [
        { id: 5, name: 'Test 5', age: 12, address: 'Shanghai' },
        { id: 6, name: 'Test 6', age: 12, address: 'Shanghai', _disabledSelect: true },
        { id: 7, name: 'Test 7', age: 12, address: 'Shanghai' },
        { id: 5, name: 'Test 5', age: 12, address: 'Shanghai' }
      ];
    }, 100);
  },
  methods: {
    setRowSelect() {
      this.$refs.table.setRowSelect(this.datas[0]);
    },
    reset() {
      this.$refs.table.clearRowSelect();
      this.$refs.table.setSelection([]);
    },
    setOddSelection() {
      this.$refs.table.setSelection(
        this.datas.filter((item, index) => (index + 1) % 2 == 1)
      );
    },
    remove(datas, data) {
      //datas.splice(datas.indexOf(data), 1);
    	//使用方法获取当前选择的对象 这里偷了个懒 用remove事件作为选择方式 
      alert(this.$refs.table.getSelection());
    },
    invereSelection() {
      this.$refs.table.invereSelection();
    },
    onselect(data, event) {
		 //alert(data)
    }
  }
};
</script>`

**Comment by wangzhaojun** [comment]
描述这个bug
单选框 this.$refs.table.getSelection()

重现步骤
1、打开 https://www.heyui.top/run
2、粘贴如下代码运行

结果如上个图,麻烦了
```
<template>
  <div>
    <p><SwitchList v-model="mode" small :datas="{'checkbox': '多选', 'rowSelect': '单选'}"></SwitchList></p>
    <p v-if="mode=='rowSelect'">
      <h-switch v-model="useRadio" small>使用Radio / Use radio</h-switch>
      <Button size="s" @click="setRowSelect">选中第一行 / Select the first line</Button>
      <Button size="s" @click="reset">清空选择 / Clear</Button>
    </p>
    <p v-else>
      <Button size="s" @click="invereSelection">反向选择 / Inverse selection</Button>
      <Button size="s" @click="setOddSelection">选择奇数列 / Select odd columns</Button>
      <Button size="s" @click="reset">清空选择 / Clear</Button>
    </p>
    <Table :datas="datas" ref="table" :height="400" @select="onselect" :checkbox="mode=='checkbox'" :selectRow="mode=='rowSelect'" :radio="mode=='rowSelect' && useRadio" selectWhenClickTr>
      <TableItem title="ID" prop="id" align="center" :width="80" fixed="left"></TableItem>
      <TableItem title="age" prop="age" :width="150"></TableItem>
      <TableItem title="address" prop="address" align="center" :width="150"></TableItem>
      <TableItem title="name" prop="name" :width="150"></TableItem>
      <TableItem title="age" prop="age" :width="150"></TableItem>
      <TableItem title="address" prop="address" align="center" :width="150"></TableItem>
      <TableItem title="name" prop="name" :width="150"></TableItem>
      <TableItem title="age" prop="age" :width="150"></TableItem>
      <TableItem title="address" prop="address" align="center" :width="150"></TableItem>
      <TableItem title="operating" align="center" :width="80" fixed="right"><template slot-scope="{data}"><button class="h-btn h-btn-s h-btn-red" @click="remove(datas, data)"><i class="h-icon-trash"></i></button></template></TableItem>
      <div slot="empty">Custom reminder: no data at this time</div>
    </Table>
  </div>
</template>

<script>
export default {
  data() {
    return {
      datas: [],
      useRadio: true,
      mode: 'rowSelect'
    };
  },
  mounted() {
    setTimeout(() => {
      this.datas = [
        { id: 5, name: 'Test 5', age: 12, address: 'Shanghai' },
        { id: 6, name: 'Test 6', age: 12, address: 'Shanghai', _disabledSelect: true },
        { id: 7, name: 'Test 7', age: 12, address: 'Shanghai' },
        { id: 5, name: 'Test 5', age: 12, address: 'Shanghai' }
      ];
    }, 100);
  },
  methods: {
    setRowSelect() {
      this.$refs.table.setRowSelect(this.datas[0]);
    },
    reset() {
      this.$refs.table.clearRowSelect();
      this.$refs.table.setSelection([]);
    },
    setOddSelection() {
      this.$refs.table.setSelection(
        this.datas.filter((item, index) => (index + 1) % 2 == 1)
      );
    },
    remove(datas, data) {
      //datas.splice(datas.indexOf(data), 1);
    	//使用方法获取当前选择的对象 这里偷了个懒 用remove事件作为选择方式 
      alert(this.$refs.table.getSelection());
    },
    invereSelection() {
      this.$refs.table.invereSelection();
    },
    onselect(data, event) {
		 //alert(data)
    }
  }
};
</script>
```

**Comment by mynetfan** [comment]
rowSelected  单选状态下被选中的项目
getSelection()  获取多选状态下被选中的项目集合
