### ISSUE TITLE
table组件是否可以增加表头分组的功能

### ISSUE THREAD

**Issue by fanzouguo** [heyui/heyui#26]

**Comment by vvpvvp** [comment]
请具体描述一下，是指表头有两行，还是有下拉筛选的功能？

**Comment by fanzouguo** [comment]
以上都不是的，类似于下图zhe'zh这种，
![default](https://user-images.githubusercontent.com/10015003/45919990-c0af7780-bed0-11e8-8b30-7ee821911dd4.png)
上图是从 iview中截过来的，见谅。不过这个也不是很满意，最终希望的是列表头和行表头都可以做合并分组，如下图这样：
![2](https://user-images.githubusercontent.com/10015003/45920002-f2284300-bed0-11e8-9175-1f16aabcbd8a.png)
很早之前在网上看到一个国外的例子实现过，现在找不到了，不过也不能用，那个有 jquery 依赖。

期待中，谢谢

**Comment by vvpvvp** [comment]
我考虑一下实现的方案。
