### ISSUE TITLE
Menu inlineCollapsed 时误触问题

### ISSUE THREAD

**Issue by kexirong** [heyui/heyui#261]
**描述这个bug**
使用Menu 的 inlineCollapsed模式时，当鼠标放到 菜单栏外 大概32像素范围（官方网文档 demo 大概16像素范围），有子菜单的item 会浮出子菜单，这样会影响页面使用

**重现步骤**

 菜单收起时，鼠标在菜单外十几像素 到几十像素处移动 会浮现 子菜单

**期望行为**

仅鼠标处于 菜单栏内 才弹出 子菜单

**截图**

  这种暂时无法截图

**Comment by vvpvvp** [comment]
并没有发生你说的那个问题啊？
你可以录屏看一下。

**Comment by kexirong** [comment]
![Peek 2019-12-16 22-37](https://user-images.githubusercontent.com/31177595/70915370-ad984280-2054-11ea-8c4f-ee0ae6566c3b.gif)
如录屏中所示，鼠标并未移入菜单栏中，但是那些子菜单会浮出，上面是heyui文档中的demo，下面是自己的页面，距离更甚
![Peek 2019-12-16 22-36](https://user-images.githubusercontent.com/31177595/70915656-30210200-2055-11ea-947b-604703fb72a7.gif)
@vvpvvp

**Comment by vvpvvp** [comment]
你使用的是什么浏览器，什么系统？
macOS Chrome上面并没有出现这种问题。

**Comment by kexirong** [comment]
chrome 79.0 ，我试了 Windows 还有 Linux(gnome) 都存在该问题，mac 晚上回去试试，理论也是存在的。对了，建议release的时候把源码也打包进去，这样方便查看源码 @vvpvvp

**Comment by vvpvvp** [comment]
源码可以直接在GitHub上查看，release还是更多考虑包大小的问题。

**Comment by vvpvvp** [comment]
还有我提供了一个未压缩的版本，你也可以通过这个版本来查看。

**Comment by kexirong** [comment]
谢谢 ，我找到了问题所在  .h-menu-show-desc  缺少  visibility: hidden 样式，经测试，问题消失，并提交了一个PR #263 @vvpvvp

**Comment by kexirong** [comment]
之前的fork没有同步到最新， 重新提交了

**Comment by kexirong** [comment]
补传mac 下的录屏，macOS下 需要点击一下demo区域，才会出现此问题
![QQ20191217-212856-HD](https://user-images.githubusercontent.com/31177595/70999696-dda71a80-2114-11ea-934d-24f0b2c0154a.gif)

**Comment by vvpvvp** [comment]
的确是有这个问题
