### ISSUE TITLE
tree

### ISSUE THREAD

**Issue by qiuguanyou** [heyui/heyui#265]
**描述这个bug**
如下图，这样有点乱，不够清晰
![image](https://user-images.githubusercontent.com/24726904/71334931-2b8baa80-257b-11ea-867c-cb5d5a17b981.png)

**期望行为**
建议加入可选线条模式
![image](https://user-images.githubusercontent.com/24726904/71335020-92a95f00-257b-11ea-9ab1-63906b212c5d.png)

**Comment by vvpvvp** [comment]
你上图显示的是table，下图是tree，建议你先看你要使用的组件到底是什么。

**Comment by qiuguanyou** [comment]
&nbsp;TreeTable&nbsp; ，希望是有一些线，区分出树的层级。这样会更清晰些。



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Lan"<notifications@github.com&gt;; 
发送时间: 2019年12月29日(星期天) 晚上7:32
收件人: "heyui/heyui"<heyui@noreply.github.com&gt;; 
抄送: "烟火里的尘埃"<570227234@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [heyui/heyui] tree (#265)




Closed #265.
 
&mdash;
