### ISSUE TITLE
建议新增锚点导航组件

### ISSUE THREAD

**Issue by qiuguanyou** [heyui/heyui#268]
**期望行为截图**
详情场景：
![image](https://user-images.githubusercontent.com/24726904/71395209-ec7b5900-264f-11ea-8207-ef766d5e17e9.png)
体验连接：[https://blog.csdn.net/shentibeitaokong/article/details/80397826](url)
表单场景：
![image](https://user-images.githubusercontent.com/24726904/71395220-fd2bcf00-264f-11ea-982a-e8f72cd79b93.png)
体验连接：[https://blog.csdn.net/weixin_43844392/article/details/89227244](url)

**Comment by vvpvvp** [comment]
你可以使用
steps
https://www.heyui.top/component/plugin/steps

ScrollIntoView 滚动至视图内
https://www.heyui.top/component/other/scrollintoview

结合使用即可
