### ISSUE TITLE
steps 优化

### ISSUE THREAD

**Issue by qiuguanyou** [heyui/heyui#269]
**描述bug截图**
![image](https://user-images.githubusercontent.com/24726904/71395492-1bde9580-2651-11ea-8743-6fd4b8be1559.png)
当步骤越多时，这里会自动挤压

**期望行为截图**
希望可以保持步骤宽度大小，不会自动挤压，当步骤多时，出现滚动条即可，像这样
![image](https://user-images.githubusercontent.com/24726904/71395575-7e379600-2651-11ea-9b63-cf08f8aa3c4e.png)
把插槽分为，三块 上、中、下 ，最好方便定制。

**Comment by vvpvvp** [comment]
我不建议这种这么长的步骤，如果步骤真的很长，你可以外层补充横向滚动条。
如果期望保持步骤宽度大小，那也可以直接使用css覆盖的方式达成。

**Comment by qiuguanyou** [comment]
是的，我现在就是这样处理的， 
我们是做企业OA的， 真正的业务需求，长的流程步骤，无法避免， 故提此建议。




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Lan"<notifications@github.com&gt;; 
发送时间: 2019年12月29日(星期天) 晚上7:30
收件人: "heyui/heyui"<heyui@noreply.github.com&gt;; 
抄送: "烟火里的尘埃"<570227234@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [heyui/heyui] steps 优化 (#269)




我不建议这种这么长的步骤，如果步骤真的很长，你可以外层补充横向滚动条。
 如果期望保持步骤宽度大小，那也可以直接使用css覆盖的方式达成。
 
&mdash;
