### ISSUE TITLE
是否可以给时间轴连接线的颜色增加自定义属性？

### ISSUE THREAD

**Issue by fanzouguo** [heyui/heyui#27]
我的主体背景是 #f2f2f2，这样一来，时间轴的连接线就看不见了。
目前我是自定义全局覆盖的样式去替换 hey的颜色，主要是用了：
/* 覆盖垂直时间轴纵线颜色 */
.h-timeline-pending .h-timeline-item:nth-last-of-type(2) .h-timeline-item-content:after {
  border-left: 1px #555 dotted !important;
}

.h-timeline-item-content:after {
  content: "";
  border-left: 1px #333 dashed !important;
}

但不知道为什么最后一个节点的连接线会超出节点那个圆圈。所以我想还是通过组件提供属性比较好。
考虑到 hey 用了两种颜色（应该是吧），可以设定该属性的值为数组，个人建议。

**Comment by vvpvvp** [comment]
主题颜色定义的问题，其实我建议还是使用覆盖的形式，class比较好定义与修改。
如果使用属性定义的话，其实后期再覆盖会比较麻烦，而且基本上时间轴一个系统不会出很多类型的样式。
至于节点超出的问题，已经修正，等待更新就好了。
