### ISSUE TITLE
NumberInput的chang事件直接搞成blur事件这样做真的合适？

### ISSUE THREAD

**Issue by btboys** [heyui/heyui#273]
NumberInput的chang事件直接搞成blur事件这样做真的合适？

**Comment by vvpvvp** [comment]
https://developer.mozilla.org/zh-CN/docs/Web/Events/change
![image](https://user-images.githubusercontent.com/7303371/97384991-c7a8df80-190b-11eb-91ed-cdd0165ce8de.png)
