### ISSUE TITLE
www.heyui.top 这个文档网站怎么本地安装

### ISSUE THREAD

**Issue by iskylite** [heyui/heyui#281]
工作是在离线环境下，查个东西比较麻烦，想把https://www.heyui.top/ 这个网站安装在本地服务器上，方便查看组件啥的。请问是否可以给个源码？若果不行。。。

**Comment by vvpvvp** [comment]
你下载下来，确认安装了hey-cli
``` 
npm install
cd doc
npm install
hey dev
```
