### ISSUE TITLE
 询问框 如果不定义取消事件会报错

### ISSUE THREAD

**Issue by JHeLiu** [heyui/heyui#284]
![image](https://user-images.githubusercontent.com/15246138/76677402-d656b680-6608-11ea-850e-4092eeec4f31.png)

询问框 如果不定义取消事件会报错

这个是官方文档 也报错了

**Comment by vvpvvp** [comment]
这个的确是有历史问题，当时参考了element的设计，使用了promise的用法，但是，这个的确是不合理的。本身取消按钮作为关闭按钮，不做处理是正常的，但是由于已经提供了这个功能，就不能再删除了。

未来等大的第二个改版，这个方法将全部改成回调函数。
