### ISSUE TITLE
建议增强表格组件拖拽调节列宽、单元格内容过长省略显示

### ISSUE THREAD

**Issue by qiuguanyou** [heyui/heyui#287]
1、拖拽调节列宽
2、单元格内容过长省略显示 ，最好支持table 全局属性（整个表格开启） 、单个单元格设置省略
![image](https://user-images.githubusercontent.com/24726904/77510350-8352ee00-6ea9-11ea-813a-ec26fd8632d1.png)

**Comment by vvpvvp** [comment]
我觉得这个可以👌，我会考虑补充一下。
