### ISSUE TITLE
使用HSwitch修改store的值时 会Vue Warn

### ISSUE THREAD

**Issue by nshusr** [heyui/heyui#291]
**描述这个bug**
HSwitch默认会执行setter 在手动修改store的时候，便会Log Warn，望修复

**重现步骤**
步骤:  
https://codesandbox.io/s/heyui-demos-2xsm0?file=/src/App.vue
切换HSwitch状态便会Log
`[Vue warn]: Computed property was assigned to but it has no setter.`

**期望行为**
不打Log

**Comment by kexirong** [comment]
这个是你使用规范的问题，而且这个log是vue的行为
