### ISSUE TITLE
使用按需加载，全局方法不可用，如何配置？

### ISSUE THREAD

**Issue by kexirong** [heyui/heyui#292]
求助，
使用按需加载后，如 v-wordlimt 等全局方法不可用，
文档中也无 Directive插件 相关配置说明，
![image](https://user-images.githubusercontent.com/31177595/83248602-e594db80-a1d7-11ea-8796-bfd42e86cbeb.png)

**Comment by vvpvvp** [comment]
![image](https://user-images.githubusercontent.com/7303371/91113995-6ff6b980-e6b9-11ea-905e-75600718316e.png)
https://github.com/heyui/heyui/blob/master/src/components/prototypes/index.js
在prototypes里面

**Comment by kexirong** [comment]
v-wordlimt 这些用不了
