### ISSUE TITLE
TextEllipsis 超出文本省略不支持响应式

### ISSUE THREAD

**Issue by 0xAC7** [heyui/heyui#296]
**描述这个bug**
浏览器窗口缩放时，TextEllipsis 文本依然会超出容器。

**重现步骤**
步骤:  
1. 打开 https://www.heyui.top/component/other/textellipsis
2. F12 打开开发者工具，置于右侧
3. 拖动开发者工具窗口让 demo 示例的容器宽度变窄

**期望行为**
当窗口缩放时，依然可以支持文本自动省略。

**截图**
如果可以，添加屏幕截图帮助解释您的问题。

**请完整的描述以下信息**
 - 操作系统[比如 WIN10]
 - 浏览器[比如 chrome, safari]
 - 版本[比如 22]

**补充信息**
在这里添加关于问题的任何其他补充信息。

**Comment by vvpvvp** [comment]
这个是因为，我把宽度写了，这个是可以自适应的。
