### ISSUE TITLE
文档属性名称错误，作者这是要停更了麽？

### ISSUE THREAD

**Issue by btboys** [heyui/heyui#301]
![image](https://user-images.githubusercontent.com/841976/89391183-6d4c1880-d73a-11ea-8b2e-1d108c001d4f.png)

**Comment by MayBeWrong** [comment]
大半年没啥提交了，看起来貌似要弃坑啊

**Comment by JHeLiu** [comment]
好可惜的库，停更了就难受了。

**Comment by vvpvvp** [comment]
已经修正了。
没有弃坑，阿里太忙了，哭.........
