### ISSUE TITLE
建议TreePicker参数type为key时支持初始化数据

### ISSUE THREAD

**Issue by ChartWay** [heyui/heyui#310]
`model的类型，注意：key模式不支持初始化传入数据，因为对应的title展示不出来`

- 本质上key是常用的,object不常用
- 虽然使用object可以达到需求,但毕竟需要额外处理object数据
- 让key去选中选项理论上不难

所以,建议TreePicker参数type为key时支持初始化数据

**Comment by vvpvvp** [comment]
已经支持了，我忘记这里还有这句话了。
![image](https://user-images.githubusercontent.com/7303371/97261025-ef8b3b00-1858-11eb-8f51-8ebff93cf7a0.png)
