### ISSUE TITLE
急需Uploader组件

### ISSUE THREAD

**Issue by ChartWay** [heyui/heyui#312]
现在的uploader组件点击没反应，说明文档乱七八糟，根本调不通，QQ群也没有回复消息，Uploader是非常常用的组件，但是包里面的竟然不能用，项目停在这个地方了，难道要为一个组件跟换框架？但是我还是非常喜欢Heyui的，整体上设计思路比其他框架优秀。希望作者能够加快提供Uploader组件。谢谢！

**Comment by vvpvvp** [comment]
实在是不好意思，这么迟才回复。
然后Upload组件，其实本质上可以自己直接用Form自己来写的，这一块我的确写的不是很好，后期会重新编写。
官网的示例已经恢复了。
