### ISSUE TITLE
建议TagInput组件增加远程搜索功能

### ISSUE THREAD

**Issue by ChartWay** [heyui/heyui#317]
1、远程搜索主要是让标签输入者可以选择需要的标签，避免创建过多相似标签，分散聚合力度
2、远程搜索需要作为可选项，即由开发者配置是否使用远程搜索
3、即便使用远程搜索，用户也可以输入不在远程的标签（搜索的目的是减少相似标签，并不是只能搜索）

**Comment by vvpvvp** [comment]
你直接使用autocomplete就可以了。
因为远程搜索是一个大功能，所以这个需求是并在autocomplete组件中。你说的应该都可以支持到。
