### ISSUE TITLE
Menu组件的 Active 状态是否可以开放出 API，便于自行辅助控制。

### ISSUE THREAD

**Issue by fanzouguo** [heyui/heyui#33]
组件自身已经处理了 Active状态，但是留一个控制接口自行处理会更完善一些，比如：
> 菜单一
> 菜单二
> 菜单三

当我点击过“菜单二”，再点击“菜单三”，然后点击浏览器的回退，此时菜单项中，受 Active状态控制的样式依然停留在菜单二上。
当然这个现象可以作为bug处理掉，但还有些属于页面元素点击跳转，而非菜单触发的情景，也需要菜单项的Active状态做出响应，所以增加一个自定义的API会是比较好的办法。

**Comment by vvpvvp** [comment]
已经有这种方法了，请参考menu组件页面的第一个demo。

**Comment by fanzouguo** [comment]
我刚刚试过DEMO里的方法，但是要通过 $refs 来获取，如果我跨组件，在某些生命周期无法获取到 $refs的时候就没办法了。
![default](https://user-images.githubusercontent.com/10015003/46655148-563f4c80-cbdd-11e8-8bb7-83013f8184cd.png)
所以我在想，是不是可以某种方法，比如监听全局事件之类的，或者是不是我的方法不对，请指教一下，谢谢

**Comment by fanzouguo** [comment]
或者加一个 activeKey 这类的参数，我用 vuex 来管理

**Comment by fanzouguo** [comment]
我现在临时的处理办法是：
<div></div>
<Menu ref="menu" .....></Menu>

<script>
  computed: {
    getMenuActive: function() {
     let _key = this.getCurrMenuKey;   // getCurrMenuKey是 vuex 里的一个 getter
     if (_key) {
       this.toggleMenuIitem(_key);
     }
    }
  },
  methods: {
    toggleMenuIitem: function(key) {
       this.$refs.testMenu.select(key);    // 失败
      console.log(this.$refs.testMenu);


       this.$refs.testMenu.$refs.menu.select(key);  // 成功
      console.log(this.$refs.testMenu.$refs.menu);
    }
  }
</script>

问题是： 直接调用 this.$refs.XXX.select() 不行，必须使用  this.$refs.XXX.$refs.menu.select()，不知道为什么。


![refs_testmenu](https://user-images.githubusercontent.com/10015003/46658431-4af01f00-cbe5-11e8-817d-d906dd0751cd.jpg)

---

![refs_testmenu_refs_menu](https://user-images.githubusercontent.com/10015003/46658455-55aab400-cbe5-11e8-815a-1cea62fb9243.jpg)

**Comment by vvpvvp** [comment]
我觉得你的思路有点绕弯了。
你跳转list-1，或者list-2，都应该是跳转路由。
然后在menu的组件里面监听组件变化就可以了。

其实整体架构，你都可以参考hey-admin，基本上能囊括90%的开发需求。
我后面的一个月将对hey-admin做全面的说明。

你可以参考：
https://github.com/heyui/heyui-admin/blob/master/src/components/app/app-menu.vue

``` html
  watch: {
    $route() {
      this.menuSelect();
    }
  },
  mounted() {
    this.menuSelect();
  },
  methods: {
    menuSelect() {
      if (this.$route.name) {
        this.$refs.menu.select(this.$route.name);
      }
    },
    trigger(data) {
      this.$router.push({ name: data.key });
    }
  }
```

**Comment by fanzouguo** [comment]
豁然开朗了，十分感谢。之前就是有点迷糊
