### ISSUE TITLE
询问textellipsis.vue的设计思路

### ISSUE THREAD

**Issue by PmcFizz** [heyui/heyui#342]
你好，我是一名前端开发者， 朋友推荐我使用heyui，真的帮到我了很多。
我在使用textellipsis.vue组件时，觉得这真是一个神奇的组件，于是看了[源码](https://github.com/heyui/heyui/blob/master/src/components/text-ellipsis/textellipsis.vue#L75)， 但看了很多还是有几处不太明白。希望大佬能够再百忙之中为小弟解惑一下。
主要是下面这段代码。

```js
while (title.offsetHeight > this.height && n > 0) {
  if (title.offsetHeight > this.height * 3) {
    textDom.innerText = text = text.substring(0, Math.floor(text.length / 2));
  } else {
    textDom.innerText = text = text.substring(0, text.length - 1);
  }
  n--;
}
```

* 问题1：为什么要判断`title.offsetHeight`与 `this.height * 3`的大小？这里的3 有什么特殊含有吗？
* 问题2：使用n=1000 来遍历，是不是会有很多无用的遍历？

@vvpvvp 

非常感谢大佬对开源界的无私奉献。

**Comment by vvpvvp** [comment]
很开心我的作品被认可，毕竟我很久没有更新了。
问题1：为什么要判断title.offsetHeight与 this.height * 3的大小？这里的3 有什么特殊含有吗？
第一个判断是为了快速截断，比如：文本超过一万个文字，那一个一个文字删减，性能很差，n=1000遍历完毕也无法满足，所以如果高度超出预期的3倍，则按照一半的量来做删减

问题2：使用n=1000 来遍历，是不是会有很多无用的遍历？
你仔细看下while的判断，title.offsetHeight > this.height && n > 0，不是只有n的判断，所以当文字截断生效的时候title.offsetHeight > this.height，遍历就会结束，n=1000的遍历不是循环下限，而是为了意外情况产生的遍历上限。

最近在更新vue3.0，欢迎提供更多的支持与建议。

**Comment by PmcFizz** [comment]
谢谢大佬的耐心解答，让我收益良多。
