### ISSUE TITLE
作者厉害了，能否增加Transfer窗口和Collapse 折叠面板

### ISSUE THREAD

**Issue by 54yuri** [heyui/heyui#35]
作者厉害了，
Transfer窗口
Collapse 折叠面板
Carousel 走马灯

iview 和element-ui也都有这样的功能
有没有这样的计划加上？
这样就能把element-ui 和 iview的功能都给涵盖了，用这样的功能的人不少。用起来也更有口碑！
希望作者能把他们加上，祝heyui发展越来越好
非常感谢！

**Comment by vvpvvp** [comment]
多谢你的建议，我会尽快补齐这3个组件的。
之前没有加，主要是我们没有太多的这种需求，我看了一下，我觉得你说的这三种还是挺好的，我这边会排期的。
最后，多谢支持。
