### ISSUE TITLE
你好，几个特性咨询下

### ISSUE THREAD

**Issue by pugwoo** [heyui/heyui#4]
1. 能否像elementUI一样打包成独立的js和css，这样后台开发时不需要安装nodejs环境

2. 树形控件能否支持拖拽节点

谢谢！

**Comment by limodou** [comment]
+1

**Comment by vvpvvp** [comment]
你好，我回复一下：
1. 能否像elementUI一样打包成独立的js和css，这样后台开发时不需要安装nodejs环境
可以，但是目前来说，如果不使用webpack的模式，vue还没有达到最大的开发效果，所以其实我们的主场景都是放在webpack+es6+vue文件上的。
然后，[hey-cli](https://github.com/heyui/hey-cli)已经大大的减低了webpack等配置难度。

2. 树形控件能否支持拖拽节点
目前，并不支持拖拽，可以考虑后期支持。

**Comment by vvpvvp** [comment]
独立的js和css：
https://www.heyui.top/simple.html
文档：http://localhost:9008/component/quickstart

**Comment by pugwoo** [comment]
非常感谢，希望后续都同步发布独立版的js和css哈，为你们点赞！
