### ISSUE TITLE
为啥呢？

### ISSUE THREAD

**Issue by zhangjw-ECHO** [heyui/heyui#42]
[Vue warn]: Error in mounted hook: "TypeError: Cannot read property 'getConfig' of undefined"

found in

---> <HFormItem> at /Users/alicia/Documents/develop/github/heyui/heyui/src/components/form/formItem.vue
       <HForm> at /Users/alicia/Documents/develop/github/heyui/heyui/src/components/form/form.vue
         <Root>
warn @ vue.js:584
vue.js:1719 TypeError: Cannot read property 'getConfig' of undefined
    at VueComponent.mounted (heyui.js:10)
    at callHook (vue.js:2895)
    at Object.insert (vue.js:4084)
    at invokeInsertHook (vue.js:5851)
    at Vue$3.patch [as __patch__] (vue.js:6070)
    at Vue$3.Vue._update (vue.js:2637)
    at Vue$3.updateComponent (vue.js:2765)
    at Watcher.get (vue.js:3113)
    at new Watcher (vue.js:3102)
    at mountComponent (vue.js:2772)
logError @ vue.js:1719
vue.js:584 [Vue warn]: Error in mounted hook: "TypeError: Cannot read property 'getConfig' of undefined"

found in

---> <HFormItem> at /Users/alicia/Documents/develop/github/heyui/heyui/src/components/form/formItem.vue
       <HForm> at /Users/alicia/Documents/develop/github/heyui/heyui/src/components/form/form.vue
         <Root>
warn @ vue.js:584
vue.js:1719 TypeError: Cannot read property 'getConfig' of undefined
    at VueComponent.mounted (heyui.js:10)
    at callHook (vue.js:2895)
    at Object.insert (vue.js:4084)
    at invokeInsertHook (vue.js:5851)
    at Vue$3.patch [as __patch__] (vue.js:6070)
    at Vue$3.Vue._update (vue.js:2637)
    at Vue$3.updateComponent (vue.js:2765)
    at Watcher.get (vue.js:3113)
    at new Watcher (vue.js:3102)
    at mountComponent (vue.js:2772)
logError @ vue.js:1719
vue.js:584 [Vue warn]: Error in mounted hook: "TypeError: Cannot read property 'getConfig' of undefined"

found in

---> <HFormItem> at /Users/alicia/Documents/develop/github/heyui/heyui/src/components/form/formItem.vue
       <HForm> at /Users/alicia/Documents/develop/github/heyui/heyui/src/components/form/form.vue
         <Root>
warn @ vue.js:584
vue.js:1719 TypeError: Cannot read property 'getConfig' of undefined
    at VueComponent.mounted (heyui.js:10)
    at callHook (vue.js:2895)
    at Object.insert (vue.js:4084)
    at invokeInsertHook (vue.js:5851)
    at Vue$3.patch [as __patch__] (vue.js:6070)
    at Vue$3.Vue._update (vue.js:2637)
    at Vue$3.updateComponent (vue.js:2765)
    at Watcher.get (vue.js:3113)
    at new Watcher (vue.js:3102)
    at mountComponent (vue.js:2772)
logError @ vue.js:1719
vue.js:584 [Vue warn]: Error in mounted hook: "TypeError: Cannot read property 'getConfig' of undefined"

found in

---> <HFormItem> at /Users/alicia/Documents/develop/github/heyui/heyui/src/components/form/formItem.vue
       <HForm> at /Users/alicia/Documents/develop/github/heyui/heyui/src/components/form/form.vue
         <Root>
warn @ vue.js:584
vue.js:1719 TypeError: Cannot read property 'getConfig' of undefined
    at VueComponent.mounted (heyui.js:10)
    at callHook (vue.js:2895)
    at Object.insert (vue.js:4084)
    at invokeInsertHook (vue.js:5851)
    at Vue$3.patch [as __patch__] (vue.js:6070)
    at Vue$3.Vue._update (vue.js:2637)
    at Vue$3.updateComponent (vue.js:2765)
    at Watcher.get (vue.js:3113)
    at new Watcher (vue.js:3102)
    at mountComponent (vue.js:2772)

**Comment by vvpvvp** [comment]
没有场景，只有报错，我也不知道原因啊？

**Comment by zhangjw-ECHO** [comment]
我直接在html引入得js和css 
TypeError: Cannot read property 'getConfig' of undefined
    at o.mounted (heyui:14)
    at _t (vue:6)
    at Object.insert (vue:6)
    at A (vue:6)
    at hn.__patch__ (vue:6)
    at hn._update (vue:6)
    at hn.<anonymous> (vue:6)
    at St.get (vue:6)
    at new St (vue:6)
    at hn.$mount (vue:6)

<!DOCTYPE html>
<html lang="en" xmlns:v-on="http://www.w3.org/1999/xhtml" xmlns:th="http://www.thymeleaf.org"
      xmlns:sec="http://www.thymeleaf.org/thymeleaf-extras-springsecurity3">
<head>
    <meta charset="UTF-8">
    <title>角色管理</title>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/>
    <script th:inline="javascript" type="text/javascript" rel="script" src="../axios/axios.min.js"></script>
    <script th:inline="javascript" type="text/javascript" rel="script" src="../axios/qs.js"></script>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/heyui/themes/index.css"></link>
    <script th:inline="javascript" type="text/javascript" rel="script" src="../axios/ajax.js"></script>
</head>
<body>

<div id="app1" v-padding="20">
    <div class="h-panel">
    <div class="h-panel-bar">
        <span class="h-panel-title">角色添加</span>
        <span v-color:gray v-font="13"></span>
    </div>
    <div class="h-panel-bar">
        <div class="h-btn-group">
            <button class="h-btn" @click="submit"><i class="h-icon-inbox"></i><span>保存</span></button>
            <button class="h-btn"><i class="h-icon-trash"></i><span>取消</span></button>
        </div>
    </div>
    <div class="h-panel-body bottom-line">
        <h-form ref="form" :label-width="150" :rules="rules" :model="data">
            <h-form-item label="角色名称" prop="roleName">
                <input type="text" v-model="data.roleName" />
            </h-form-item>
            <h-formitem label="角色类型" prop="roleType">
                <h-select v-model="data.roleType" :datas="roleTypes" placeholder="请选择角色类型" null-option-text="请选择角色类型"></h-select>
            </h-formitem>
            <h-form-item label="数据对象" prop="dataObject">
                <input type="text" v-model="data.dataObject" />
            </h-form-item>
            <h-form-item label="描述" prop="description">
                <input type="text" v-model="data.description" />
            </h-form-item>
        </h-form>
    </div>
</div>
</div>
<script>
    var app = new Vue({
        el: '#app1',
        data() {
            return {
                labelPosition: "left",
                data: {

                },
                roleTypes: [],
                rules: {
                    required: ['roleName','roleType']
                },
                isLoading: false,
            }
        },
        methods: {
            submit(){
                axios({
                    url:'saverole',
                    method:'post',
                    headers: {'Content-Type': 'application/x-www-form-urlencoded'},
                    data: Qs.stringify(this.data)
                }).then(responese => {
                    if (responese.status == 200) {
                        const d = responese.data;
                        console.log(d)
                        if (d.success) {
                            alert(d.data);
                        } else {
                            alert(d.error)
                        }

                    }
                });
            },
        },
        components: {
        },
        mounted(){
            axios.get('../dict/getdatabytype/roleType').then(response => {
                if (response.status == 200) {
                    const data = response.data.data;
                    for (let d of data) {
                        const obj = {'key':d.value,'title':d.label};
                        this.roleTypes.push(obj)
                    }
                }
            });
        }

    })
</script>

<script th:inline="javascript" src="https://cdn.jsdelivr.net/npm/vue"></script>
<script th:inline="javascript" src="https://cdn.jsdelivr.net/npm/heyui"></script>
</body>
</html>

**Comment by zhangjw-ECHO** [comment]
<div id="app1" v-padding="20">
    <div class="h-panel">
    <div class="h-panel-bar">
        <span class="h-panel-title">角色添加</span>
        <span v-color:gray v-font="13"></span>
    </div>
    <div class="h-panel-bar">
        <div class="h-btn-group">
            <button class="h-btn" @click="submit"><i class="h-icon-inbox"></i><span>保存</span></button>
            <button class="h-btn"><i class="h-icon-trash"></i><span>取消</span></button>
        </div>
    </div>
    <div class="h-panel-body bottom-line">
        <h-form ref="form" :label-width="150" :rules="rules" :model="data">
            <h-form-item label="角色名称" prop="roleName">
                <input type="text" v-model="data.roleName" />
            </h-form-item>
            <h-formitem label="角色类型" prop="roleType">
                <h-select v-model="data.roleType" :datas="roleTypes" placeholder="请选择角色类型" null-option-text="请选择角色类型"></h-select>
            </h-formitem>
            <h-form-item label="数据对象" prop="dataObject">
                <input type="text" v-model="data.dataObject" />
            </h-form-item>
            <h-form-item label="描述" prop="description">
                <input type="text" v-model="data.description" />
            </h-form-item>
        </h-form>
    </div>
</div>
</div>

**Comment by WingGao** [comment]
这个和 #45 是一样的，已修复了
