### ISSUE TITLE
浏览器模式下modal参数属性不管用

### ISSUE THREAD

**Issue by hotlt** [heyui/heyui#52]
请问，浏览器模式下（直接引用cdn），Modal组件设置:hasDivider="true" :closeOnMask="false"都不起作用是为什么？

**Comment by hotlt** [comment]
解决了，驼峰写法的问题。换成 :has-divider="true" :close-on-mask="false" 就可以了

**Comment by hotlt** [comment]
但是宽度设置还是不起作用。 :width="600"，请问怎么解决？

**Comment by vvpvvp** [comment]
不好意思，width暂时没有作为属性定义在modal组件上，js调用支持。
想要设定宽度，直接设定modal内部调用的dom的宽度即可。
