### ISSUE TITLE
移动版

### ISSUE THREAD

**Issue by liyuchuan86** [heyui/heyui#6]
请问会支持移动版优化么？

**Comment by vvpvvp** [comment]
不会支持移动版，但是有可能做一个新的移动版项目。
毕竟有很多复杂的组件，其实在移动版并不需要，还有一些其他的组件，在移动端的交互方式并不一致。

**Comment by liyuchuan86** [comment]
可惜了，一直在找稍微复杂点的移动版组件，唉

**Comment by wangyi7099** [comment]
可以用vunt

**Comment by wangyi7099** [comment]
说错了  是vux
