### ISSUE TITLE
Discouraged export pattern.

### ISSUE THREAD

**Issue by atilkan** [heyui/heyui#63]
This pattern is discouraged. 
Because "JS engine cannot statically analyze the contents of plain object".

**Refering book ->** https://goo.gl/5bfwdb

Couple places i found. There are many more. 

https://github.com/heyui/heyui/blob/ed278d3f44bb4730a8d0ccec31a1de6828318d70/src/filters/index.js#L4

https://github.com/heyui/heyui/blob/ed278d3f44bb4730a8d0ccec31a1de6828318d70/src/directives/tooltip.js#L43

https://github.com/heyui/heyui/blob/ed278d3f44bb4730a8d0ccec31a1de6828318d70/src/directives/wordcount.js#L16

**Comment by vvpvvp** [comment]
I will optimize some files later, like utils.

![image](https://user-images.githubusercontent.com/7303371/53071096-2bb2b800-351c-11e9-9d98-7a142aa1a228.png)

**Comment by atilkan** [comment]
@vvpvvp What is the name of the book you referring?
