### ISSUE TITLE
English translations for examples on docs

### ISSUE THREAD

**Issue by atilkan** [heyui/heyui#65]
English translations are required for examples. Are there anyone working on this? I might be able to work on this.

**Comment by vvpvvp** [comment]
At this moment, no one is working on this,  If you could help me, that would be wonderful.

**Comment by atilkan** [comment]
@vvpvvp I am working on this. Please reopen the issue and close when merge happens.

**Comment by vvpvvp** [comment]
I've already released it. You can go to the official website and have a look.

**Comment by vvpvvp** [comment]
Thank you very much for your support.

**Comment by atilkan** [comment]
@vvpvvp Looks great. Thank you.

**Comment by atilkan** [comment]
@vvpvvp There is some problems on example codes. I may be done something wrong. It shows compiled code on examples.

![screen shot 2019-03-05 at 18 04 08](https://user-images.githubusercontent.com/1254613/53814715-3421de80-3f71-11e9-8a2a-857bd18cecac.png)

**Comment by vvpvvp** [comment]
Where did this mistake happen? I can't see it on the screenshot. @atilkan

**Comment by atilkan** [comment]
@vvpvvp It is on every component detail when you Expand Code.

**Comment by vvpvvp** [comment]
I've fixed this problem.

Commit: https://github.com/heyui/heyui/commit/e20ad539f9cc98b552e9c54ca2d83eec51575bda

**Comment by atilkan** [comment]
@vvpvvp Thanks. Looks great.
