### ISSUE TITLE
ROADMAP

### ISSUE THREAD

**Issue by atilkan** [heyui/heyui#67]
Please add a roadmap.

**Comment by vvpvvp** [comment]
What kind of roadmap?

**Comment by vvpvvp** [comment]
![image](https://user-images.githubusercontent.com/7303371/53310548-515b0b00-38e8-11e9-9004-7b738438ab60.png)

How about this?

**Comment by atilkan** [comment]
@vvpvvp 
General kind :) Like a todo list. 
Like listing what features will be implemented, what translations should be done.

**Comment by vvpvvp** [comment]
I see. So what tools do you think I should use?

**Comment by atilkan** [comment]
@vvpvvp draw.io And the image above would help too.

Example: https://github.com/adam-golab/react-developer-roadmap

**Comment by vvpvvp** [comment]
I'm a little confused. What you mean is that I created a roadmap to become a developer of heyui or a roadmap of the heyui development plan?

**Comment by atilkan** [comment]
This one -> **roadmap of the heyui development plan**

**Comment by vvpvvp** [comment]
I'm a little busy these days, and I've been thinking about it for a long time, but I still haven't thought about how to use mind mapping to draw development plans. If you can provide an effective example, it would be better.

**Comment by atilkan** [comment]
It is better if you do it when you have time. I don't know what to do.

**Comment by vvpvvp** [comment]
It would be better if you provided a demo pr.

**Comment by atilkan** [comment]
@vvpvvp I don't know what to call it but i am trying to figure what can we do for help. For example, bugs, documents, type definitions, anything i can work on.

**Comment by vvpvvp** [comment]
https://github.com/heyui/heyui/projects/3
