### ISSUE TITLE
heyui  js 体积过大该怎么办？

### ISSUE THREAD

**Issue by lizhongyi** [heyui/heyui#7]
很喜欢heyui的颜值深得我心，hey dev 开发模式也很棒，当时我遇到了一个尴尬的问题，build之后的common.js  体积高大500kb，在带宽的小的阿里云上面加载时间经常需要几秒钟，其实我只是用了很少的一部分组件。

我想是否有一种开发方式，可以享受 hey-cli  的便利，又能组件按需加载，或者可以讲多个第三库内连在 script 标签下面，可以通过cdn并行加载来提高加载速度，当然我看了，heyui simple方案，确实很不错，就是无法去使用 开发环境了。希望能得到帮助

**Comment by vvpvvp** [comment]
你好，hey dev的方式也可以使用heyui simple的方案的。
请参考：
https://github.com/heyui/hey-cli#external-loading-vuevue-router

关于组件按需加载，目前的确是没有做拆分，主要是由于HeyUI的整体机制是集成了数据驱动，所以有一些难以拆分，后期，我会想办法看能不能解决这个问题。

最后，多谢支持🙏。
