### ISSUE TITLE
Category组件   getDatas只在初次渲染组件时触发一次 后续不会触发

### ISSUE THREAD

**Issue by Thornchg** [heyui/heyui#70]
如题 
getDatas只在初次渲染时会执行一次
后续怎么点击都无法触发

不知道是不是我写的方式有问题
可以给个Demo吗
因为项目数据量大
想要在点击父项后再请求子项

**Comment by vvpvvp** [comment]
目前， Category组件暂时不支持分布异步加载，我们这边会尽快把异步加载的功能补充完毕。
