### ISSUE TITLE
Collapse v-model 值变变更后，activedKeys未同步

### ISSUE THREAD

**Issue by btboys** [heyui/heyui#71]
Collapse组件的v-model 值变变更后，activedKeys未同步

**Comment by vvpvvp** [comment]
activedKeys? 没有这个相关属性啊？

**Comment by btboys** [comment]
> activedKeys? 没有这个相关属性啊？

.....你自己写的组件，难道你没印象麽。。。。  [collapse.vue](https://github.com/heyui/heyui/blob/master/src/components/collapse/collapse.vue)的26行，我觉得你需要watch value属性的变化。不然没法手动修改collapse的选中项

**Comment by vvpvvp** [comment]
sorry,  我理解成Category组件了，这个我会在下期迭代中补充上。

周五上线。

**Comment by yoga021** [comment]
hi ~ watch value 已加，上线之后就可以看到了。
关于列表更新重置keys的问题，应该是开发者自己去关注。
