### ISSUE TITLE
动态生成表单，校验机制失效

### ISSUE THREAD

**Issue by gaollg** [heyui/heyui#72]
**描述这个bug**
Hey UI 动态生成表单，校验机制失效。复现链接：https://runjs.cn/code/vj7eeegm

**问题描述**
光标离开时，可以触发错识，然调用 valid() 失效。

**排查过程**

以下代码，说明 Dom 确实没问题，着重是 valid() 方法调试
![image](https://user-images.githubusercontent.com/2359462/54188315-650e9000-44ea-11e9-8ce6-6813bf7364b7.png)

Debug 如图：这是光标离开 DOM 后，触发错误，result: true，messages 却包含错误信息。
![image](https://user-images.githubusercontent.com/2359462/54188401-95562e80-44ea-11e9-8c04-8ae00aefd2c0.png)

未压缩代码对比：https://github.com/heyui/heyui/blob/master/src/components/form/form.vue
![image](https://user-images.githubusercontent.com/2359462/54188450-ab63ef00-44ea-11e9-95c4-0b7493fdc5a5.png)

**猜测**
可能是 validator 插件有 BUG。

**Comment by gaollg** [comment]
![image](https://user-images.githubusercontent.com/2359462/54196430-634dc800-44fc-11e9-8d24-d49d615b5b8a.png)

补充详细 Debug 信息，注意右上角 Watch 变量“n”、“i”信息。

**Comment by vvpvvp** [comment]
![image](https://user-images.githubusercontent.com/7303371/54202862-ea566c80-450b-11e9-9628-d73f7ded828d.png)


https://runjs.cn/code/vd7nvbil

**Comment by gaollg** [comment]
![image](https://user-images.githubusercontent.com/2359462/54206894-2a215200-4514-11e9-99cb-95fda5408b73.png)

多谢，原来是校验对象必须要有值，概因是动态表单，只能用如图所示方法，强行给赋值。问题是，Model 对象的校验值不存在，不是也应该校验失败才对呀？

**Comment by vvpvvp** [comment]
我昨天晚上也想了一下，的确是有这个问题，但是这个修改牵扯很多，我后期会对这块做优化的，多谢。
