### ISSUE TITLE
如何编译heyui

### ISSUE THREAD

**Issue by limodou** [heyui/heyui#8]
运行 npm run build 说 hey 找不到。也没有看到其它的编译方式。

运行 p min build 都不行。

**Comment by vvpvvp** [comment]
编译heyui？
你的需求是什么？

**Comment by limodou** [comment]
自已生成css和js。这样如果我改了heyui的代码可以测试。

**Comment by vvpvvp** [comment]
你好，你可以通过安装使用 [hey-cli](https://github.com/heyui/hey-cli) 的方式进行编译。
