### ISSUE TITLE
希望增加 Cascader 级联选择组件

### ISSUE THREAD

**Issue by mcmf** [heyui/heyui#81]
希望增加  Cascader 组件

**Comment by vvpvvp** [comment]
建议直接使用TreePicker组件，不知道你们的 Cascader 组件 主要是用来选择什么类型的数据？

**Comment by vvpvvp** [comment]
我们计划开发AddressPicker，地址选择组件。

**Comment by mcmf** [comment]
tree 结构都需要Cascader 组件

**Comment by vvpvvp** [comment]
我们已经有TreePicker组件了
