### ISSUE TITLE
编译出现 @skeleton-height is undefined 问题

### ISSUE THREAD

**Issue by htom78** [heyui/heyui#85]
**描述这个bug**
执行npm run serve,  
会出现
Variable @skeleton-height is undefined

**重现步骤**
步骤:  
删除node_modules 和package-lock.json 重新执行 npm install 后执行npm run serve 即可发现

 ERROR  Failed to compile with 1 errors                                                                    下午8:43:49

 error  in ./src/css/app.less

Module build failed (from ./node_modules/less-loader/dist/cjs.js):

    .h-skeleton-title {
      height: @skeleton-height;
            ^
Variable @skeleton-height is undefined
      in /Users/kaka/Codes/9102/front/node_modules/heyui/themes/components/skeleton.less (line 16, column 14)

**请完整的描述以下信息**
 - 操作系统: Mac 10.14
 -npm 版本 6.9.0

**Comment by vvpvvp** [comment]
请更新heyui版本即可
