### ISSUE TITLE
辣鸡，引个css都这么难，抄一下ele的配置很难吗

### ISSUE THREAD

**Issue by ruanlianjun** [heyui/heyui#86]
**描述这个bug**
简洁清晰的描述这个bug是什么样子的。

**重现步骤**
步骤:  
1. 打开 '...'  
2. 点击 '....'  
3. 发现 error  

**期望行为**
清晰明了地描述你期望发生的事情。

**截图**
如果可以，添加屏幕截图帮助解释您的问题。

**请完整的描述以下信息**
 - 操作系统[比如 WIN10]
 - 浏览器[比如 chrome, safari]
 - 版本[比如 22]

**补充信息**
在这里添加关于问题的任何其他补充信息。

**Comment by vvpvvp** [comment]
不用就不用，不会用就不要用。
我没有抄袭居然成了别人辱骂的点，我也是无语了。
而且，我写的再烂，你也没有资格评判。

**Comment by mcmf** [comment]
@ruanlianjun 没见你开源项目有多牛啊  别乱BB

**Comment by ruanlianjun** [comment]
我这个弱鸡，瑟瑟发抖

**Comment by jiangningstar** [comment]
@ruanlianjun 属喷壶么~  上来就喷。。。
