### ISSUE TITLE
表单组件 label 建议

### ISSUE THREAD

**Issue by qiuguanyou** [heyui/heyui#87]

**Comment by vvpvvp** [comment]
表单组件的 label 加入图标属性和插槽，方便个性化定义，我觉得是一个挺好的建议的。

**Comment by qiuguanyou** [comment]
感谢采纳建议，后续有更多的建议，会继续反馈，愿 heyui 越做越好用 ！

**Comment by qiuguanyou** [comment]
看代码只加了插槽，也许多加一个 label-icon  属性更为方便，
一个属性即可搞定 label 文字前需要图标，但自定义不复杂的需求。

**Comment by vvpvvp** [comment]
从场景上来说，每个form的label都有一个 icon 的场景很少。
虽然说 label-icon 属性更为方便，但是使用度低。

**Comment by qiuguanyou** [comment]
![image](https://user-images.githubusercontent.com/24726904/55300314-77d11080-5469-11e9-8159-ec7ff755d52c.png)
![image](https://user-images.githubusercontent.com/24726904/55300350-9c2ced00-5469-11e9-95cb-39a2801fd298.png)
是的，当在只读表单时，会使用到。
个人觉得还是通用便捷些为好，比较走心 哈
