### ISSUE TITLE
你一个人写一整套组件库的动力是什么？

### ISSUE THREAD

**Issue by jinan5694** [heyui/heyui#9]
看到这个组件库，是你一个人完成的。我很震惊。
是什么支撑你在做这件事？
公司？个人爱好？

**Comment by vvpvvp** [comment]
大概是有时间还无聊吧......呵呵，也喜欢写代码。

**Comment by jardenliu** [comment]
可以的，虽然感觉有点像IView

**Comment by vvpvvp** [comment]
你用用就知道啦，其实本质上区别还是挺大的。
