### ISSUE TITLE
一点关于官方文档的建议

### ISSUE THREAD

**Issue by kexirong** [heyui/heyui#94]
```
目前项目初期，本人也主要是后端开发，3月初开始接触vue，尝试了多个组件库。
antd:感觉流畅度不好可能是动画原因。
elment:不喜欢scss，可供定制的变量少，定制的主要方式用wrapper，作为新手的我不太喜欢。
iview，确实不错可用性也好，但是不知道为啥就是感觉不喜欢，似乎优点挺多的
再就寻找到了heyui
```
heyui 目前还没有用, 看了两小时的官网文档, 设计思想很新颖。
有点建议忍不住想提，也不知道在issue中写会不会令人不悦
文档中，快速上手中，建议参考其它组件库，当前太简要，适合老手跟超级新手(clone heyadmin)，如果有代码能力，但webpack初接触(如后端程序员)。vue比layui更适合后端程序员
文档中icon中出现v-font ,但这个v-font没有看到说明，是vue的api，还是heyui实现的还是demo中实现的？让人疑惑
建议作者将文档中有疑惑的地方完善下，相信大多数人，在了解一个开源库的时候都是从文档开始，友好的文档，能大大增加使用兴趣。
这些只是建议，并不是吐槽

**Comment by vvpvvp** [comment]
多谢你提供的建议。
你说明的问题的确存在，因为我自己开发很多年了，所以写文档的时候，会觉得大家都知道就没有写，所以缺失很多信息，而且我其实也不太清楚大家对哪一块不是很了解。
而且，由于我的同事基本上也都是资深前端，所以，大家也提不出什么好的建议。
如果你能提供更多的帮助，我们是非常欢迎的。
你可以通过pr的方式来帮助我们补充更多的信息。
至于v-font，其实是heyui内置的，你可以参考一下https://www.heyui.top/component/basic/extend#Directive%20%E6%A0%B7%E5%BC%8F
