### ISSUE TITLE
希望heyui能增加一个颜色选择器，加一个渐变颜色选择器更好哦。

### ISSUE THREAD

**Issue by eveningwater** [heyui/heyui#95]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**
希望heyui能增加一个颜色选择器，加一个渐变颜色选择器更好哦。

**Comment by vvpvvp** [comment]
有没有考虑直接使用系统自带的颜色选择器？

**Comment by eveningwater** [comment]
> 有没有考虑直接使用系统自带的颜色选择器？
大多数情况下都不会考虑原生的颜色选择器。
