### ISSUE TITLE
Table Tabs 还有联想组件要好好优化一下

### ISSUE THREAD

**Issue by JanusJia** [heyui/heyui#96]
最近做项目选一个vue的框架，看了一下heyui还是有很多创新，比如全局的一些东西，字典，做过项目都知道这些东西经常用，不过等到项目后期的时候发现，一个框架最核心的Table，Tabs，还有自动联想组件，树组件真的只能凑合着用，体验性能还差太远了，希望能在核心的组件上多用点心

**Comment by vvpvvp** [comment]
多谢你前面的认可，但是我想说的，最核心的Table，Tabs，还有自动联想组件，树组件 都是我觉得挺满意的组件，毕竟我的设计方向和其他组件库也是不同的，Table后期我还会扩展一些，但是其他的组件，我不觉得差，如果你觉得体验性能差，请具体，比如：什么交互流畅度不行，或者什么功能不完善，不接受模糊评价。

Tabs 其实我的定义和其他的组件是不一致的，我觉得tabs是系统开发中最经常用到的东西，我提取的是tabs 的数据交互逻辑，并不包括 数据在其他地方的处理逻辑。

自动联想组件 我觉得还是比其他组件库要强大很多的。

树组件，虽然没有拖拽的功能，但是基础的功能都是具备的。
