### ISSUE TITLE
Modal 弹出框 建议可以指定局部插入

### ISSUE THREAD

**Issue by qiuguanyou** [heyui/heyui#98]
![image](https://user-images.githubusercontent.com/24726904/55863700-a2c80c80-5bad-11e9-9bfa-fd500c8f98df.png)
上图 是插入到body的 ，全局居中，和显示背景层，
但有一种情况，如果是抽屉页面，在抽屉页面层需要弹层，应该是这样的
![image](https://user-images.githubusercontent.com/24726904/55863868-f89cb480-5bad-11e9-9285-3c08d3d999d6.png)
只在抽屉页面层插入相对抽屉层居中，并且背景层只在抽屉层覆盖。

**Comment by vvpvvp** [comment]
不是非常理解这个问题，能再补充详细吗？
如果在抽屉中触发弹框，那就还是按照正常弹窗的场景啊。
如果可以的话，可以示例更好一些，多谢。

**Comment by qiuguanyou** [comment]
![image](https://user-images.githubusercontent.com/24726904/55869971-2f78c780-5bba-11e9-8223-1ac198a14387.png)
不知道这样描述是否能理解呢？  在抽屉弹层触发的，应该可以相对抽屉层居中，包括背景层。也就是说这个弹层是局部的，应该是相对它的父元素居中。

**Comment by vvpvvp** [comment]
我并不建议使用这样的设计，其实新的弹框出现在页面的居中位置，我觉得是更加合理以及交互扩展性更强的设计。

**Comment by qiuguanyou** [comment]
抽屉拉出后，然后再在抽屉点击弹层，应该属于 抽屉里局部的操作，并非全局的，个人见解，是否可以像 element-ui 提供一个 modal 插入节点位置的属性呢？ 🙏

**Comment by qiuguanyou** [comment]
![image](https://user-images.githubusercontent.com/24726904/57177237-efdd8c80-6e94-11e9-8cd4-35fc5cb61fe6.png)
