### ISSUE TITLE
建议 Select 新增可局部插入

### ISSUE THREAD

**Issue by qiuguanyou** [heyui/heyui#99]
看框架目前 Select  也全局插入到body的 ， 这样在结合 Tooltip  使用时会出现奇怪的问题。
![image](https://user-images.githubusercontent.com/24726904/55864843-d60b9b00-5baf-11e9-9f0b-100fe5a43bd6.png)
点击其中一个 选项，会导致Tooltip 关闭

**Comment by qiuguanyou** [comment]
![image](https://user-images.githubusercontent.com/24726904/55865129-5b8f4b00-5bb0-11e9-88f9-a85f87809b32.png)
建议所有动态插入 body 的组件，应该留有指定插入 元素的属性

**Comment by vvpvvp** [comment]
这个问题，我会解决的，但是不是因为你提示的这个问题导致的。

**Comment by qiuguanyou** [comment]
好的，请问怎么使用你最新修复的代码呢？  是直接安装开发版本 就可以吗？
